import { FormEvent, useState } from 'react'
import { X, CheckCircle, CircleNotch, LockKey, Fingerprint } from '@phosphor-icons/react'
import { api } from '../lib/api'
import { useBiometrics } from '../hooks/useBiometrics'
import { Logo, categoryMeta, type ModalKind } from './common'

export function Modal({ kind, workspaceId, onClose, onSubmit }: { kind: Exclude<ModalKind,null>; workspaceId: string; onClose:()=>void; onSubmit:(kind:Exclude<ModalKind,null>,body:Record<string,unknown>)=>Promise<void> }) {
  const [busy,setBusy]=useState(false),[type,setType]=useState<'income'|'expense'>('expense')
  async function submit(event:FormEvent<HTMLFormElement>) { event.preventDefault(); const fd=new FormData(event.currentTarget); const amount=Math.round(Number(String(fd.get('amount')||'0').replace(',','.'))*100); const base={workspace_id:workspaceId}; let body:Record<string,unknown>; if(kind==='transaction')body={...base,type,description:fd.get('title'),category:fd.get('category'),amount_cents:amount,date:fd.get('date'),due_date:fd.get('due_date'),status:fd.get('status')}; else if(kind==='goal')body={...base,title:fd.get('title'),target_cents:amount,current_cents:Math.round(Number(String(fd.get('current')||'0').replace(',','.'))*100),deadline:fd.get('date')}; else body={...base,title:fd.get('title'),creditor:fd.get('category'),total_cents:amount,paid_cents:Math.round(Number(String(fd.get('current')||'0').replace(',','.'))*100),due_date:fd.get('date')}; setBusy(true); try{await onSubmit(kind,body);onClose()}finally{setBusy(false)} }
  const today=new Date().toISOString().slice(0,10)
  return <div className="modal-backdrop" onMouseDown={(e)=>{if(e.currentTarget===e.target)onClose()}}><form className="modal-card" onSubmit={submit}><div className="modal-head"><div><strong>{kind==='transaction'?'Nova movimentação':kind==='goal'?'Nova meta':'Nova dívida'}</strong><small>{kind==='transaction'?'Registre uma entrada ou saída.':kind==='goal'?'Transforme um plano em progresso.':'Organize o que precisa ser quitado.'}</small></div><button type="button" onClick={onClose}><X/></button></div>{kind==='transaction'&&<div className="segmented modal-segment"><button type="button" className={type==='income'?'active':''} onClick={()=>setType('income')}>Entrada</button><button type="button" className={type==='expense'?'active':''} onClick={()=>setType('expense')}>Saída</button></div>}<label>Título<input name="title" required maxLength={100} placeholder={kind==='goal'?'Ex.: Viagem':kind==='debt'?'Ex.: Cartão de crédito':'Ex.: Supermercado'}/></label><div className="form-grid"><label>Valor (R$)<input name="amount" required inputMode="decimal" placeholder="0,00"/></label>{kind!=='transaction'&&<label>{kind==='goal'?'Já guardado (R$)':'Já pago (R$)'}<input name="current" inputMode="decimal" defaultValue="0"/></label>}</div>{kind==='transaction'&&<label>Categoria<select name="category" defaultValue="Outros">{Object.keys(categoryMeta).map(c=><option key={c}>{c}</option>)}</select></label>}{kind==='debt'&&<label>Credor<input name="category" placeholder="Banco, pessoa ou empresa"/></label>}<div className="form-grid"><label>{kind==='transaction'?'Data':'Prazo / vencimento'}<input name="date" type="date" defaultValue={today}/></label>{kind==='transaction'&&<label>Vencimento (opcional)<input name="due_date" type="date"/></label>}</div>{kind==='transaction'&&<label>Status<select name="status"><option value="paid">Pago / recebido</option><option value="pending">Pendente</option></select></label>}<button className="primary-action" disabled={busy}>{busy?<CircleNotch className="spin"/>:<CheckCircle/>}Salvar</button></form></div>
}

export function AuthPage({ onAuthenticated, notify }: { onAuthenticated:()=>Promise<void>; notify:(m:string)=>void }) {
  const [mode,setMode]=useState<'login'|'register'>('login'),[busy,setBusy]=useState(false)
  const biometrics=useBiometrics()
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const fd=new FormData(event.currentTarget);setBusy(true);try{if(mode==='login')await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:fd.get('username'),password:fd.get('password')})});else await api('/api/auth/register',{method:'POST',body:JSON.stringify({display_name:fd.get('name'),username:fd.get('username'),password:fd.get('password')})});await onAuthenticated()}catch(e){notify(e instanceof Error?e.message:'Não foi possível entrar.')}finally{setBusy(false)}}
  async function biometricLogin(){try{await biometrics.authenticateBiometrics();await onAuthenticated()}catch(e){notify(e instanceof Error?e.message:'Biometria indisponível.')}}
  return <div className="auth-shell"><div className="auth-brand"><Logo/><h1>Sua vida financeira<br/>em um novo ritmo.</h1><p>Organize, planeje e acompanhe tudo com leveza.</p></div><form className="auth-card" onSubmit={submit}><div className="segmented"><button type="button" className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Entrar</button><button type="button" className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Criar conta</button></div>{mode==='register'&&<label>Nome<input name="name" autoComplete="name" required placeholder="Seu nome"/></label>}<label>Usuário<input name="username" autoCapitalize="none" autoComplete="username" required placeholder="seu.usuario"/></label><label>Senha<input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={6} placeholder="••••••••"/></label><button className="primary-action" disabled={busy}>{busy?<CircleNotch className="spin"/>:<LockKey/>}{mode==='login'?'Entrar no Ritmo':'Criar minha conta'}</button>{mode==='login'&&biometrics.isSupported&&<><div className="auth-divider"><span>ou</span></div><button type="button" className="biometric-action" disabled={biometrics.busy} onClick={()=>void biometricLogin()}><Fingerprint/>Entrar com biometria</button></>}<small className="auth-note">Seus dados financeiros ficam protegidos por sessão segura, D1 e WebAuthn.</small></form></div>
}

export function Loading() { return <div className="loading-screen"><img src="/assets/ritmo-icon.png"/><CircleNotch className="spin"/><span>Preparando seu Ritmo...</span></div> }

export function Toast({ message }: { message:string|null }) { return message ? <div className="toast">{message}</div> : null }
