import { useState } from 'react'
import { AirplaneTilt, ShieldCheck, Laptop, Trophy, Car, CreditCard, UserCircle, CheckCircle, CaretRight, Trash, Camera, CircleNotch, CloudArrowUp, LockKey, SignOut, Sun, Moon, Desktop, Fingerprint, Bell, ListBullets, DownloadSimple, Translate, Question, MagnifyingGlass, Plus, CaretLeft, Eye, ArrowUpRight, ArrowDownRight } from '@phosphor-icons/react'
import { useBiometrics } from '../hooks/useBiometrics'
import type { BootstrapData, Debt, Goal, Transaction, Workspace } from '../types'
import { money, dateLabel, categoryMeta, StatCard, BalanceChart, DonutCard, ListCard, TransactionRow, Avatar, type Page } from './common'

export function Dashboard({ data, setPage, onAdd }: { data: BootstrapData; setPage: (p: Page) => void; onAdd: () => void }) {
  const paid = data.transactions.filter((t) => t.status === 'paid')
  const incomes = paid.filter((t) => t.type === 'income').reduce((s,t) => s+t.amount_cents,0)
  const expenses = paid.filter((t) => t.type === 'expense').reduce((s,t) => s+t.amount_cents,0)
  const pending = data.transactions.filter((t) => t.type === 'expense' && t.status === 'pending').reduce((s,t) => s+t.amount_cents,0)
  const debt = data.debts.filter((d) => d.status === 'active').reduce((s,d) => s + Math.max(0,d.total_cents-d.paid_cents),0)
  const recent = data.transactions.slice(0, 2)
  const upcoming = data.transactions.filter((t) => t.status === 'pending').slice(0, 2)
  return <><section className="stats-grid" aria-label="Resumo financeiro"><StatCard label="Saldo total" value={money(incomes - expenses)} trend={data.active_workspace.name} tone="balance" icon={Eye}/><StatCard label="Receitas" value={money(incomes)} trend="entradas confirmadas" tone="income" icon={ArrowUpRight}/><StatCard label="Despesas" value={money(expenses)} trend={pending ? `${money(pending)} pendentes` : 'sem pendências'} tone="expense" icon={ArrowDownRight}/><StatCard label="Haver (dívidas)" value={money(debt)} trend={`${data.debts.filter((d)=>d.status==='active').length} contas ativas`} tone="debt" icon={CreditCard}/></section><section className="main-grid"><BalanceChart transactions={data.transactions}/><DonutCard transactions={data.transactions}/><ListCard title="Próximas contas" action={<button onClick={() => setPage('movements')}>Ver todas</button>}>{upcoming.length ? upcoming.map(t => <TransactionRow key={t.id} item={t}/>) : <div className="empty-state">Nenhuma conta pendente.</div>}</ListCard><ListCard title="Últimas movimentações" action={<button onClick={() => setPage('movements')}>Ver todas</button>}>{recent.length ? recent.map(t => <TransactionRow key={t.id} item={t}/>) : <div className="empty-state">Comece adicionando sua primeira movimentação.</div>}</ListCard></section><button className="floating-add" onClick={onAdd} aria-label="Nova movimentação"><Plus weight="bold" /></button></>
}

export function PageHeader({ title, subtitle, onAdd }: { title: string; subtitle?: string; onAdd?: () => void }) {
  return <div className="page-head"><div><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div>{onAdd && <button className="primary-small" onClick={onAdd}><Plus weight="bold"/>Adicionar</button>}</div>
}

export function Movements({ data, onAdd, onDelete }: { data: BootstrapData; onAdd: () => void; onDelete: (t: Transaction) => void }) {
  const [filter, setFilter] = useState<'Todas'|'Entradas'|'Saídas'>('Todas')
  const [query, setQuery] = useState('')
  const list = data.transactions.filter((t) => (filter === 'Todas' || (filter === 'Entradas' && t.type === 'income') || (filter === 'Saídas' && t.type === 'expense')) && `${t.description} ${t.category}`.toLowerCase().includes(query.toLowerCase()))
  return <><PageHeader title="Movimentações" subtitle="Acompanhe tudo que entra e sai." onAdd={onAdd}/><div className="segmented" role="tablist">{(['Todas','Entradas','Saídas'] as const).map(x => <button key={x} className={filter===x?'active':''} onClick={() => setFilter(x)}>{x}</button>)}</div><label className="search search--page"><MagnifyingGlass/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar movimentações..."/></label><div className="filter-row"><button>{data.active_workspace.name}<CaretRight/></button><button>{list.length} itens</button></div><section className="card movement-list"><h2>Movimentações</h2>{list.length ? list.map(t => <TransactionRow key={t.id} item={t} onDelete={onDelete}/>) : <div className="empty-state">Nenhum resultado por aqui.</div>}</section></>
}

export function Goals({ data, onAdd, onDelete }: { data: BootstrapData; onAdd: () => void; onDelete: (g: Goal) => void }) {
  return <><PageHeader title="Metas" subtitle="Seus planos, cada vez mais perto." onAdd={onAdd}/><div className="segmented"><button className="active">Minhas metas</button><button>Conquistas</button></div><div className="goal-grid">{data.goals.map((g,i) => { const progress = Math.min(100, Math.round(g.current_cents / Math.max(1,g.target_cents)*100)); const Icon=[AirplaneTilt,ShieldCheck,Laptop][i%3]; const tone=['blue','green','navy'][i%3]; return <article className="card goal-card" key={g.id}><span className={`goal-icon ${tone}`}><Icon weight="fill"/></span><div><span>{g.title}</span><strong>{money(g.target_cents)}</strong></div><span className="percent">{progress}%</span><div className="progress"><i style={{width:`${progress}%`}}/></div><small>{money(g.current_cents)} de {money(g.target_cents)}{g.deadline ? <><br/>Até {dateLabel(g.deadline)}</> : null}</small><button className="goal-arrow row-delete" onClick={() => onDelete(g)} aria-label={`Excluir ${g.title}`}><Trash/></button></article> })}</div>{!data.goals.length && <div className="card empty-big">Crie sua primeira meta e acompanhe o progresso no seu ritmo.</div>}<div className="achievement"><Trophy weight="fill"/><div><strong>Pequenos passos constroem grandes conquistas.</strong><span>O progresso das suas metas aparece aqui.</span></div><CaretRight/></div></>
}

export function Debts({ data, onAdd, onDelete }: { data: BootstrapData; onAdd: () => void; onDelete: (d: Debt) => void }) {
  const active = data.debts.filter((d) => d.status === 'active')
  const debtTotal = active.reduce((s,d) => s + Math.max(0,d.total_cents-d.paid_cents),0)
  return <><PageHeader title="Dívidas" subtitle="Controle para respirar com mais liberdade." onAdd={onAdd}/><div className="segmented"><button className="active">Ativas ({active.length})</button><button>Quitadas ({data.debts.length-active.length})</button></div><div className="debt-total"><span>Haver total</span><strong>{money(debtTotal)}</strong><CreditCard weight="fill"/></div><div className="debt-grid">{data.debts.map((d,i) => { const progress = d.total_cents ? Math.min(100,Math.round(d.paid_cents/d.total_cents*100)) : 0; const Icon=i%2?Car:CreditCard; const tone=['purple','yellow','green','orange'][i%4]; return <article className="card debt-card" key={d.id}><span className={`row-icon ${tone}`}><Icon weight="fill"/></span><div className="debt-copy"><strong>{d.title}</strong><small>{d.creditor || 'Dívida'}{d.due_date ? ` · vence ${dateLabel(d.due_date)}` : ''}</small></div><strong>{money(Math.max(0,d.total_cents-d.paid_cents))}</strong><div className="progress"><i style={{width:`${progress}%`}}/></div><small>{progress}%</small><button className="row-delete debt-delete" onClick={() => onDelete(d)} aria-label={`Excluir ${d.title}`}><Trash/></button></article> })}</div>{!data.debts.length && <div className="card empty-big">Nenhuma dívida cadastrada.</div>}</>
}

export function CalendarPage({ data }: { data: BootstrapData }) {
  const [cursor, setCursor] = useState(() => new Date())
  const year=cursor.getFullYear(), month=cursor.getMonth()
  const first = new Date(year,month,1).getDay(), total = new Date(year,month+1,0).getDate()
  const cells = Array.from({length:42},(_,i) => { const day=i-first+1; return day>=1&&day<=total?day:null })
  const prefix=`${year}-${String(month+1).padStart(2,'0')}`
  const dates = new Set(data.transactions.filter((t)=>t.date.startsWith(prefix) || t.due_date?.startsWith(prefix)).flatMap((t)=>[t.date,t.due_date]).filter(Boolean).map((v)=>Number(String(v).slice(8,10))))
  const [selected,setSelected]=useState(new Date().getDate())
  const selectedDate=`${prefix}-${String(selected).padStart(2,'0')}`
  const events=data.transactions.filter((t)=>t.date===selectedDate||t.due_date===selectedDate)
  const monthName=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(cursor)
  return <><PageHeader title="Calendário" subtitle={monthName.charAt(0).toUpperCase()+monthName.slice(1)}/><section className="card calendar-card"><div className="calendar-tools"><button onClick={()=>setCursor(new Date(year,month-1,1))} aria-label="Mês anterior"><CaretLeft/></button><strong>{monthName}</strong><button onClick={()=>setCursor(new Date(year,month+1,1))} aria-label="Próximo mês"><CaretRight/></button></div><div className="weekdays">{'DSTQQSS'.split('').map((d,i)=><span key={i}>{d}</span>)}</div><div className="days">{cells.map((d,i)=><button key={i} disabled={!d} onClick={()=>d&&setSelected(d)} className={d===selected?'selected':(d&&dates.has(d)?'marked':'')}>{d}</button>)}</div></section><ListCard title={`${String(selected).padStart(2,'0')} de ${monthName.split(' ')[0]}`}>{events.length?events.map(t=><TransactionRow key={t.id} item={t}/>):<div className="empty-state">Sem compromissos financeiros neste dia.</div>}</ListCard></>
}

export function Reports({ data }: { data: BootstrapData }) { return <><PageHeader title="Relatórios" subtitle="Entenda para onde seu dinheiro está indo."/><section className="report-layout"><BalanceChart transactions={data.transactions}/><DonutCard transactions={data.transactions}/></section></> }

export function Profiles({ data, onSwitch }: { data: BootstrapData; onSwitch: (workspace: Workspace) => void }) {
  return <><PageHeader title="Seus perfis" subtitle="Escolha como deseja usar o Ritmo no momento."/><div className="profile-cards">{data.workspaces.map((workspace) => <button className={`card choice ${workspace.id===data.active_workspace.id?'active':''}`} key={workspace.id} onClick={()=>onSwitch(workspace)}><span className={`choice-icon ${workspace.type==='personal'?'green':'yellow'}`}><UserCircle weight="fill"/></span><div><strong>{workspace.name}</strong><p>{workspace.type==='personal'?'Suas finanças pessoais, seus objetivos, seu progresso.':'Finanças compartilhadas para organizar a vida em conjunto.'}</p></div>{workspace.id===data.active_workspace.id?<CheckCircle weight="fill"/>:<CaretRight/>}</button>)}</div><p className="helper-copy">Você pode alternar entre os perfis a qualquer momento. Cada lançamento fica isolado no perfil em que foi criado.</p></>
}

export function Profile({ data, onSave, onLogout, onAvatar, cacheKey }: { data: BootstrapData; onSave: (displayName:string,username:string)=>Promise<void>; onLogout:()=>Promise<void>; onAvatar:(file:File)=>Promise<void>; cacheKey:number }) {
  const [name,setName]=useState(data.profile.display_name),[username,setUsername]=useState(data.profile.username),[busy,setBusy]=useState(false)
  return <><PageHeader title="Perfil"/><section className="profile-hero"><div className="profile-avatar-wrap"><Avatar profile={data.profile} cacheKey={cacheKey}/><label className="avatar-upload"><Camera/><input type="file" accept="image/*" onChange={(e)=>{const file=e.target.files?.[0];if(file)void onAvatar(file)}}/></label></div><h2>{data.profile.display_name}</h2><p>@{data.profile.username}</p><small>Conta protegida e sincronizada pelo Ritmo.</small></section><section className="card profile-form"><label>Nome<input value={name} onChange={(e)=>setName(e.target.value)}/></label><label>Usuário<input value={username} onChange={(e)=>setUsername(e.target.value)}/></label><button className="primary-action" disabled={busy} onClick={async()=>{setBusy(true);try{await onSave(name,username)}finally{setBusy(false)}}}>{busy?<CircleNotch className="spin"/>:<CheckCircle/>}Salvar alterações</button></section><section className="card profile-list"><button><ShieldCheck/><span>Conta e segurança</span><small>WebAuthn + sessão segura</small><CaretRight/></button><button><CloudArrowUp/><span>Sincronização</span><small>D1 + modo offline</small><CaretRight/></button><button><LockKey/><span>Privacidade</span><small>Dados isolados por perfil</small><CaretRight/></button></section><button className="signout" onClick={()=>void onLogout()}><SignOut/>Sair da conta</button></>
}

export function Settings({ data, onTheme, notify }: { data: BootstrapData; onTheme:(theme:'light'|'dark'|'system')=>Promise<void>; notify:(message:string)=>void }) {
  const biometrics = useBiometrics()
  const themes:[typeof data.settings.theme,string,typeof Sun][]=[['light','Tema claro',Sun],['dark','Tema escuro',Moon],['system','Padrão do sistema',Desktop]]
  return <><PageHeader title="Temas e Configurações"/><h2 className="group-title">Aparência</h2><div className="theme-options">{themes.map(([id,label,Icon])=><button key={id} className={`theme-card ${data.settings.theme===id?'selected':''}`} onClick={()=>void onTheme(id)}><Icon/><div><strong>{label}</strong><span>{id==='system'?'Acompanha o dispositivo':'Aplicar em todo o Ritmo'}</span></div>{data.settings.theme===id?<CheckCircle weight="fill"/>:<CaretRight/>}</button>)}</div><h2 className="group-title">Segurança</h2><section className="card profile-list"><button disabled={!biometrics.isSupported||biometrics.busy} onClick={async()=>{try{await biometrics.registerBiometrics();notify('Biometria cadastrada com sucesso.')}catch(e){notify(e instanceof Error?e.message:'Não foi possível cadastrar.')}}}><Fingerprint/><span>Biometria nativa</span><small>{data.passkeys ? `${data.passkeys} credencial(is)` : biometrics.isPlatformAvailable?'Disponível neste aparelho':'Verificar disponibilidade'}</small><CaretRight/></button><button><Bell/><span>Notificações</span><CaretRight/></button><button><ListBullets/><span>Categorias</span><CaretRight/></button><button><DownloadSimple/><span>Exportar dados</span><CaretRight/></button><button><Translate/><span>Idioma</span><small>Português (Brasil)</small><CaretRight/></button><button><Question/><span>Sobre o Ritmo</span><CaretRight/></button></section></>
}
