from pathlib import Path
import sys
root=Path(sys.argv[1]);app=root/'public'/'app.js';worker=root/'_worker.js';cssp=root/'public'/'styles.css';a=app.read_text();w=worker.read_text();css=cssp.read_text()
def bounds(name):
 s=[a.find(f'function {name}('),a.find(f'async function {name}(')];s=[x for x in s if x>=0]
 if not s: raise SystemExit('Função não encontrada: '+name)
 p=min(s);q=min([x for x in [a.find('\nfunction ',p+1),a.find('\nasync function ',p+1)] if x>=0] or [len(a)]);return p,q
def fn(name,code):
 global a;p,q=bounds(name);a=a[:p]+code+a[q:]
def repa(old,new,label):
 global a
 if old not in a: raise SystemExit('APP trecho não encontrado: '+label)
 a=a.replace(old,new,1)
def repw(old,new,label):
 global w
 if old not in w: raise SystemExit('WORKER trecho não encontrado: '+label)
 w=w.replace(old,new,1)
fn('debtCard',r'''function debtEventIsAV(e){return e?.kind==='pagamento'&&String(e?.notes||'').startsWith('[AV]')}
function debtEventLabel(e){return e?.kind==='haver'?'Haver':debtEventIsAV(e)?'AV':'Pagamento'}
function debtCard(d){const balance=debtCurrentBalance(d),paid=debtCurrentPaid(d),pct=d.total_amount?Math.min(100,Math.round(paid/d.total_amount*100)):0,events=state.data.debt_events.filter(e=>e.debt_id===d.id),st=debtDueState(d);return `<article class="debt-card"><div class="debt-head"><div><h3>${esc(d.creditor)}</h3><div class="meta">Valor original ${money(d.total_amount)}${d.due_date?` • vence ${dateBR(d.due_date)}`:''}${authorNote(d)}</div></div><span class="status ${st.cls}">${st.label}</span></div><div class="card-number">${money(balance)}</div><div class="card-sub">saldo devedor atual</div><div class="progress"><i style="width:${pct}%"></i></div><div class="card-sub">${pct}% efetivamente abatido</div><div class="debt-actions debt-actions-three"><button class="btn btn-secondary" data-debt-payment="${d.id}" ${balance<=0?'disabled':''}>Pagamento</button><button class="btn btn-secondary debt-av-btn" data-debt-av="${d.id}" ${balance<=0?'disabled':''}>AV</button><button class="btn btn-secondary" data-debt-credit="${d.id}" ${balance<=0?'disabled':''}>Haver</button></div>${events.length?`<div class="event-list">${events.slice(0,5).map(e=>`<div class="event ${debtEventIsAV(e)?'av-event':''}"><span>${debtEventLabel(e)} • ${dateBR(e.date)}${authorNote(e)}</span><div><strong>${money(e.amount)}</strong> <button class="mini-btn" data-delete-event="${e.id}">×</button></div></div>`).join('')}</div>`:''}<div class="debt-sync-note">${ic('check',13)} Pagamentos e AVs entram automaticamente em Saídas.</div><div class="card-actions"><button class="mini-btn" data-edit="debt" data-id="${d.id}">${ic('edit',12)} Editar</button><button class="mini-btn" data-delete="debt" data-id="${d.id}">${ic('trash',12)} Excluir</button></div></article>`}''')
fn('itemMoney',r'''function itemMoney(x,type){const st=type==='income'?incomeState(x):expenseState(x),isIncome=type==='income',linked=x.origin==='divida'&&x.debt_event_id;return `<article class="item-card ${linked?'debt-linked-item':''}"><div class="item-line"><div><h3>${esc(x.description)}</h3><p>${esc(x.category)} • ${dateBR(x.date)}${x.due_date?` • vence ${dateBR(x.due_date)}`:''}${linked?' • sincronizado com dívida':''}${authorNote(x)}</p><span class="status ${st.cls}">${st.label}</span></div><span class="amount ${isIncome?'in':'out'}">${isIncome?'+':'−'} ${money(x.amount)}</span></div><div class="card-actions">${linked?`<button class="mini-btn" data-page="debts">${ic('wallet',12)} Gerenciar na dívida</button>`:`<button class="mini-btn" data-edit="${type}" data-id="${x.id}">${ic('edit',12)} Editar</button>${isIncome&&!incomeIsRealized(x)?`<button class="mini-btn" data-receive-income="${x.id}">${ic('check',12)} Marcar recebido</button>`:''}${!isIncome&&!expenseIsRealized(x)?`<button class="mini-btn" data-pay-expense="${x.id}">${ic('check',12)} Marcar pago</button>`:''}<button class="mini-btn" data-delete="${type}" data-id="${x.id}">${ic('trash',12)} Excluir</button>`}</div></article>`}''')
repa("if(type==='payment'||type==='credit'){const d=state.data.debts.find(x=>x.id===m.debtId);title=type==='payment'?'Registrar pagamento':'Registrar haver';fields=`<div class=\"full\" style=\"font-size:11px;color:var(--muted);margin-bottom:8px\">Saldo atual: <strong>${money(debtCurrentBalance(d||{}))}</strong></div>${moneyInput('amount',type==='payment'?'Valor pago':'Valor do haver')}","if(type==='payment'||type==='credit'||type==='av'){const d=state.data.debts.find(x=>x.id===m.debtId);title=type==='payment'?'Registrar pagamento':type==='av'?'Registrar AV':'Registrar haver';fields=`<div class=\"debt-action-context full\"><small>Saldo atual</small><strong>${money(debtCurrentBalance(d||{}))}</strong>${type==='av'?'<em>O AV reduz a dívida e entra automaticamente em Saídas.</em>':''}</div>${moneyInput('amount',type==='payment'?'Valor pago':type==='av'?'Valor do AV':'Valor do haver')}",'modal AV')
repa("if(['payment','credit','contribution'].includes(m.type)&&o.date>financeToday())","if(['payment','credit','av','contribution'].includes(m.type)&&o.date>financeToday())",'validacao AV')
repa("else if(m.type==='payment')path=`${scopePrefix()}/debts/${m.debtId}/payment`;else if(m.type==='credit')","else if(m.type==='payment')path=`${scopePrefix()}/debts/${m.debtId}/payment`;else if(m.type==='av')path=`${scopePrefix()}/debts/${m.debtId}/av`;else if(m.type==='credit')",'rota frontend AV')
repa("$$('[data-debt-payment]').forEach(b=>b.onclick=()=>{state.modal={type:'payment',debtId:b.dataset.debtPayment};renderApp(false)});$$('[data-debt-credit]')","$$('[data-debt-payment]').forEach(b=>b.onclick=()=>{state.modal={type:'payment',debtId:b.dataset.debtPayment};renderApp(false)});$$('[data-debt-av]').forEach(b=>b.onclick=()=>{state.modal={type:'av',debtId:b.dataset.debtAv};renderApp(false)});$$('[data-debt-credit]')",'bind AV')
repw("m=path.match(/^\\/api\\/debts\\/([a-f0-9-]+)\\/(payment|credit)$/i);","m=path.match(/^\\/api\\/debts\\/([a-f0-9-]+)\\/(payment|credit|av)$/i);",'regex pessoal')
repw("const debtId=m[1],kind=m[2]==='payment'?'pagamento':'haver';const d=await debtBalance", "const debtId=m[1],action=m[2],isAv=action==='av',kind=action==='credit'?'haver':'pagamento';const d=await debtBalance",'acao pessoal')
repw("const eventId=uid(),date=b.date||today();const stmts=[env.DB.prepare(`INSERT INTO debt_events(id,user_id,debt_id,kind,amount,date,notes,cash_received,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(eventId,userId,debtId,kind,amount,date,b.notes||null,b.cash_received?1:0,now(),now())];","const eventId=uid(),date=b.date||today(),eventNotes=isAv?`[AV]${b.notes?` ${String(b.notes).trim()}`:''}`:(b.notes||null);const stmts=[env.DB.prepare(`INSERT INTO debt_events(id,user_id,debt_id,kind,amount,date,notes,cash_received,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(eventId,userId,debtId,kind,amount,date,eventNotes,b.cash_received?1:0,now(),now())];",'marker pessoal')
repw(".bind(uid(),userId,`Pagamento de dívida`, 'Dívidas',amount,date,date,'pago'", ".bind(uid(),userId,isAv?'AV da dívida':'Pagamento de dívida','Dívidas',amount,date,date,'pago'",'saida pessoal')
repw("sharedMatch=path.match(/^\\/api\\/shared\\/debts\\/([a-f0-9-]+)\\/(payment|credit)$/i);","sharedMatch=path.match(/^\\/api\\/shared\\/debts\\/([a-f0-9-]+)\\/(payment|credit|av)$/i);",'regex casal')
repw("const debtId=sharedMatch[1],kind=sharedMatch[2]==='payment'?'pagamento':'haver',d=await sharedDebtBalance", "const debtId=sharedMatch[1],action=sharedMatch[2],isAv=action==='av',kind=action==='credit'?'haver':'pagamento',d=await sharedDebtBalance",'acao casal')
repw("const eventId=uid(),date=b.date||today(),stmts=[env.DB.prepare(`INSERT INTO shared_debt_events(id,partnership_id,created_by,debt_id,kind,amount,date,notes,cash_received,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(eventId,p.id,userId,debtId,kind,amount,date,b.notes||null,b.cash_received?1:0,now(),now())];","const eventId=uid(),date=b.date||today(),eventNotes=isAv?`[AV]${b.notes?` ${String(b.notes).trim()}`:''}`:(b.notes||null),stmts=[env.DB.prepare(`INSERT INTO shared_debt_events(id,partnership_id,created_by,debt_id,kind,amount,date,notes,cash_received,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(eventId,p.id,userId,debtId,kind,amount,date,eventNotes,b.cash_received?1:0,now(),now())];",'marker casal')
repw(".bind(uid(),p.id,userId,userId,'Pagamento de dívida','Dívidas',amount,date,date", ".bind(uid(),p.id,userId,userId,isAv?'AV da dívida':'Pagamento de dívida','Dívidas',amount,date,date",'saida casal')
app.write_text(a);worker.write_text(w)
css+=r'''
.debt-actions-three{grid-template-columns:repeat(3,1fr)!important}.debt-av-btn{border-color:color-mix(in srgb,var(--gold) 45%,var(--line))!important;color:var(--gold)!important}.debt-sync-note{margin-top:9px;padding:8px 10px;border-radius:11px;background:color-mix(in srgb,var(--gold) 7%,var(--surface2));color:var(--muted);font-size:8.5px}.event.av-event{background:color-mix(in srgb,var(--gold) 8%,var(--surface2))}.debt-linked-item{border-color:color-mix(in srgb,var(--gold) 18%,var(--line))}.debt-action-context{padding:10px 12px;border-radius:14px;background:var(--surface2)}.debt-action-context small,.debt-action-context strong,.debt-action-context em{display:block}.debt-action-context em{font-size:8px;color:var(--muted);font-style:normal;margin-top:2px}
@media(max-width:760px){.debt-actions-three{gap:6px!important}.debt-actions-three .btn{padding-inline:7px!important;font-size:9px!important}}
''';cssp.write_text(css)
print('AV sincronizado aplicado.')
