from pathlib import Path
import sys
from ritmo_v1_patch_utils import js_function_bounds

root=Path(sys.argv[1])
app=root/'public'/'app.js'; cssp=root/'public'/'styles.css'
a=app.read_text(); css=cssp.read_text()

def replace_func(src,name,code):
    p,q=js_function_bounds(src,name); return src[:p]+code+src[q:]

# -----------------------------------------------------------------------------
# Home: Pessoal e Casal são perfis financeiros reais. A Home tem UM seletor.
# Nas telas internas, o contexto aparece em uma barra compacta, sem duplicar UI.
# -----------------------------------------------------------------------------
scope_switcher=r'''function scopeSwitcher(){if(!sharedActive()||state.page==='home'||!['income','expenses','debts','goals','calendar','insights'].includes(state.page))return '';const shared=state.data.scope==='shared',partner=state.data.sharing?.partner?.name?.split(' ')[0]||'parceiro';return `<div class="premium-scope-dock" aria-label="Perfil financeiro ativo"><div class="premium-scope-copy"><span class="premium-scope-icon ${shared?'couple':'personal'}">${ic(shared?'users':'user',15)}</span><div><small>PERFIL ATIVO</small><strong>${shared?'Casal':'Pessoal'}</strong><span>${shared?`Com ${esc(partner)}`:'Somente seu dinheiro'}</span></div></div><div class="premium-scope-segment"><button type="button" data-scope="personal" class="${!shared?'active':''}" aria-pressed="${!shared}">Pessoal</button><button type="button" data-scope="shared" class="${shared?'active':''}" aria-pressed="${shared}">Casal</button></div></div>`}'''
a=replace_func(a,'scopeSwitcher',scope_switcher)

profile_overview=r'''function walletOverviewHtml(){const d=state.data||{},w=d.wallet||{},sh=d.sharing||{},me=d.profile||{},shared=d.scope==='shared',active=sharedActive(),partner=sh.partner||{},meFirst=(me.name||'Você').split(' ')[0],partnerFirst=(partner.name||'Parceiro').split(' ')[0],balance=shared?Number(w.shared_balance||0):Number(w.personal_balance||0),movement=shared?Number(w.shared_transfers||0):Number(w.sent_to_shared||0);return `<section class="finance-profile-shell ${shared?'couple':'personal'}"><div class="finance-profile-switch" role="tablist" aria-label="Escolher perfil financeiro"><button type="button" role="tab" aria-selected="${!shared}" class="${!shared?'active':''}" data-scope="personal"><span class="switch-avatar personal">${initials(me.name||'Você')}</span><span><small>PERFIL</small><strong>Pessoal</strong></span><i>${!shared?ic('check',12):''}</i></button>${active?`<button type="button" role="tab" aria-selected="${shared}" class="${shared?'active':''}" data-scope="shared"><span class="switch-avatar couple">${initials(me.name||'Você')}</span><span class="switch-avatar couple partner">${initials(partner.name||'Parceiro')}</span><span class="switch-copy"><small>PERFIL</small><strong>Casal</strong></span><i>${shared?ic('check',12):''}</i></button>`:''}</div><article class="finance-profile-card"><div class="finance-profile-head"><div class="finance-profile-identity">${shared?`<div class="couple-profile-avatars"><span>${initials(me.name||'Você')}</span><span>${initials(partner.name||'Parceiro')}</span></div>`:`<span class="solo-profile-avatar">${initials(me.name||'Você')}</span>`}<div><small>${shared?'PERFIL DO CASAL':'PERFIL PESSOAL'}</small><h1>${shared?`${esc(meFirst)} & ${esc(partnerFirst)}`:esc(me.name||'Meu Ritmo')}</h1><p>${shared?'O dinheiro que vocês escolheram cuidar juntos.':'Seu dinheiro, suas decisões e seu histórico.'}</p></div></div><span class="profile-badge ${shared?'shared':'personal'}">${ic(shared?'users':'user',12)} ${shared?'Casal':'Pessoal'}</span></div><div class="finance-profile-value"><span>${shared?'Saldo compartilhado':'Meu saldo'}</span><strong>${money(balance)}</strong><small>${shared?`${money(movement)} recebidos em contribuições`:`${money(movement)} enviados ao casal`}</small></div><div class="finance-profile-actions">${active?`<button type="button" class="profile-action primary" data-transfer-new>${ic('up',14)}<span>Transferir</span></button>`:''}<button type="button" class="profile-action" data-page="reports">${ic('doc',14)}<span>Relatório</span></button>${shared?`<button type="button" class="profile-action" data-page="sharing">${ic('users',14)}<span>Detalhes do casal</span></button>`:''}</div></article></section>`}'''
a=replace_func(a,'walletOverviewHtml',profile_overview)

home=r'''function homePage(){const shared=state.data.scope==='shared',s=currentStats(),commitments=[...state.data.expenses.filter(x=>!expenseIsRealized(x)&&(x.due_date||x.date)).map(x=>({type:'expense',date:x.due_date||x.date,item:x})),...state.data.debts.filter(x=>debtCurrentBalance(x)>0&&x.due_date).map(x=>({type:'debt',date:x.due_date,item:x}))].sort((x,y)=>x.date.localeCompare(y.date)).slice(0,4);return `${walletOverviewHtml()}<section class="premium-home-section"><div class="premium-section-title"><div><span class="eyebrow">VISÃO GERAL</span><h2>${shared?'Finanças do casal':'Suas finanças'}</h2></div><small>${shared?'Somente o que pertence ao casal.':'Somente a sua carteira pessoal.'}</small></div><div class="premium-summary-grid"><article><small>A receber</small><strong>${money(s.receivable)}</strong><span>${s.receivableCount||0} lançamento(s)</span></article><article><small>A pagar</small><strong>${money(s.pending)}</strong><span>${s.pendingCount||0} compromisso(s)</span></article><article><small>Projeção</small><strong>${money(s.forecast)}</strong><span>Após previstos</span></article></div><div class="premium-flow-grid"><button type="button" class="premium-flow-card income" data-page="income"><span class="premium-flow-icon">${ic('up',16)}</span><div><small>ENTRADAS</small><strong>${money(s.income)}</strong><p>Receita realizada</p></div>${ic('chev',13)}</button><button type="button" class="premium-flow-card expense" data-page="expenses"><span class="premium-flow-icon">${ic('down',16)}</span><div><small>SAÍDAS</small><strong>${money(s.paid)}</strong><p>Pagamentos realizados</p></div>${ic('chev',13)}</button><button type="button" class="premium-flow-card pending" data-page="calendar"><span class="premium-flow-icon">${ic('calendar',16)}</span><div><small>PENDENTE</small><strong>${money(s.pending)}</strong><p>Próximos compromissos</p></div>${ic('chev',13)}</button><button type="button" class="premium-flow-card debt" data-page="debts"><span class="premium-flow-icon">${ic('wallet',16)}</span><div><small>DÍVIDAS</small><strong>${money(s.debt)}</strong><p>Saldo devedor</p></div>${ic('chev',13)}</button></div></section><div class="grid2 premium-home-lower"><section class="panel premium-panel"><div class="panel-title"><div><h3>Próximos compromissos</h3><small>O que merece sua atenção agora.</small></div><button class="mini-btn" data-page="calendar">Calendário</button></div><div class="list">${commitments.length?commitments.map(x=>rowHtml(x.item,x.type)).join(''):`<div class="empty premium-empty">Tudo tranquilo por aqui. ✨</div>`}</div></section><section class="panel premium-panel"><div class="panel-title"><div><h3>${shared?'Contribuições recentes':'Transferências para o casal'}</h3><small>${shared?'Quanto cada pessoa colocou em comum.':'Movimentações da sua carteira pessoal.'}</small></div><button class="mini-btn" data-page="reports">Relatório</button></div>${shared?walletContributionRows():transferHistoryHtml(4)}</section></div>`}'''
a=replace_func(a,'homePage',home)

# -----------------------------------------------------------------------------
# CSS premium global: hierarquia consistente, cards compactos, safe-area real e
# componentes que funcionam nos temas claro/escuro sem sobreposição.
# -----------------------------------------------------------------------------
css += r'''

/* Ritmo V1 — Premium UI/UX unificada */
.main{padding-bottom:calc(116px + env(safe-area-inset-bottom,0px))!important}
.page.active{min-width:0}
.premium-scope-dock{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:9px 10px;margin:0 0 16px;border:1px solid color-mix(in srgb,var(--line) 62%,transparent);border-radius:18px;background:color-mix(in srgb,var(--surface-solid) 94%,transparent);box-shadow:0 8px 26px rgba(0,0,0,.035)}
.premium-scope-copy{display:flex;align-items:center;gap:9px;min-width:0}.premium-scope-copy>div{min-width:0}.premium-scope-copy small{display:block;font-size:7px;letter-spacing:.13em;color:var(--muted);font-weight:800}.premium-scope-copy strong{display:inline;font-size:10px}.premium-scope-copy span:last-child{margin-left:6px;font-size:8px;color:var(--muted)}
.premium-scope-icon{width:34px;height:34px;border-radius:11px;display:grid;place-items:center;flex:0 0 auto}.premium-scope-icon.personal{background:color-mix(in srgb,var(--primary) 10%,var(--surface2));color:var(--primary)}.premium-scope-icon.couple{background:color-mix(in srgb,var(--green) 11%,var(--surface2));color:var(--green)}
.premium-scope-segment{display:flex;gap:3px;padding:3px;background:var(--surface2);border-radius:12px}.premium-scope-segment button{border:0;background:transparent;color:var(--muted);font:inherit;font-size:8px;font-weight:800;padding:7px 10px;border-radius:9px;cursor:pointer}.premium-scope-segment button.active{background:var(--surface-solid);color:var(--text);box-shadow:0 3px 10px rgba(0,0,0,.05)}
.finance-profile-shell{margin:0 0 22px}.finance-profile-switch{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin:0 0 10px}.finance-profile-switch:has(button:only-child){grid-template-columns:1fr}
.finance-profile-switch button{position:relative;border:1px solid color-mix(in srgb,var(--line) 60%,transparent);background:color-mix(in srgb,var(--surface-solid) 91%,transparent);color:var(--muted);border-radius:16px;min-height:58px;padding:9px 11px;display:flex;align-items:center;gap:8px;text-align:left;cursor:pointer;box-shadow:0 5px 16px rgba(0,0,0,.025);transition:transform .16s ease,border-color .16s ease,background .16s ease}.finance-profile-switch button:active{transform:scale(.985)}.finance-profile-switch button.active{background:var(--surface-solid);border-color:color-mix(in srgb,var(--primary) 24%,var(--line));color:var(--text);box-shadow:0 9px 24px rgba(0,0,0,.06)}.finance-profile-shell.couple .finance-profile-switch button.active{border-color:color-mix(in srgb,var(--green) 28%,var(--line))}
.finance-profile-switch button>i{margin-left:auto;color:var(--primary);width:16px;height:16px}.finance-profile-shell.couple .finance-profile-switch button.active>i{color:var(--green)}.finance-profile-switch button small{display:block;font-size:7px;letter-spacing:.12em;color:var(--muted);font-weight:800}.finance-profile-switch button strong{display:block;font-size:10px;margin-top:3px}.switch-copy{min-width:0}
.switch-avatar{width:34px;height:34px;border-radius:11px;display:grid;place-items:center;font-size:9px;font-weight:850;flex:0 0 auto}.switch-avatar.personal{background:color-mix(in srgb,var(--primary) 10%,var(--surface2));color:var(--primary)}.switch-avatar.couple{background:color-mix(in srgb,var(--green) 11%,var(--surface2));color:var(--green)}.switch-avatar.couple.partner{margin-left:-13px;box-shadow:0 0 0 3px var(--surface-solid)}
.finance-profile-card{position:relative;overflow:hidden;border-radius:24px;padding:18px;background:linear-gradient(145deg,color-mix(in srgb,var(--surface-solid) 96%,var(--primary) 4%),var(--surface-solid));border:1px solid color-mix(in srgb,var(--line) 64%,transparent);box-shadow:0 18px 42px rgba(0,0,0,.07)}.finance-profile-shell.couple .finance-profile-card{background:linear-gradient(145deg,color-mix(in srgb,var(--surface-solid) 95%,var(--green) 5%),var(--surface-solid))}
.finance-profile-card:after{content:'';position:absolute;width:230px;height:230px;border-radius:50%;right:-110px;top:-135px;border:1px solid color-mix(in srgb,var(--primary) 10%,transparent);box-shadow:0 0 0 34px color-mix(in srgb,var(--primary) 2.5%,transparent),0 0 0 68px color-mix(in srgb,var(--primary) 1.7%,transparent);pointer-events:none}.finance-profile-shell.couple .finance-profile-card:after{border-color:color-mix(in srgb,var(--green) 12%,transparent);box-shadow:0 0 0 34px color-mix(in srgb,var(--green) 2.5%,transparent),0 0 0 68px color-mix(in srgb,var(--green) 1.7%,transparent)}
.finance-profile-head{position:relative;z-index:1;display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.finance-profile-identity{display:flex;align-items:center;gap:11px;min-width:0}.finance-profile-identity>div:last-child{min-width:0}.finance-profile-identity small{display:block;color:var(--primary);font-size:7px;font-weight:850;letter-spacing:.14em}.finance-profile-shell.couple .finance-profile-identity small{color:var(--green)}.finance-profile-identity h1{font-size:17px;line-height:1.1;margin:4px 0 3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.finance-profile-identity p{font-size:8.5px;line-height:1.4;color:var(--muted);margin:0;max-width:360px}
.solo-profile-avatar,.couple-profile-avatars span{width:44px;height:44px;border-radius:14px;display:grid;place-items:center;font-weight:850;font-size:11px;background:color-mix(in srgb,var(--primary) 10%,var(--surface2));color:var(--primary);border:1px solid color-mix(in srgb,var(--primary) 13%,transparent)}.couple-profile-avatars{display:flex;align-items:center;padding-right:8px}.couple-profile-avatars span{background:color-mix(in srgb,var(--green) 12%,var(--surface2));color:var(--green);border-color:color-mix(in srgb,var(--green) 14%,transparent)}.couple-profile-avatars span+span{margin-left:-11px;box-shadow:0 0 0 3px var(--surface-solid)}
.profile-badge{display:inline-flex;align-items:center;gap:5px;padding:6px 8px;border-radius:999px;font-size:7px;font-weight:850;white-space:nowrap}.profile-badge.personal{background:color-mix(in srgb,var(--primary) 8%,transparent);color:var(--primary)}.profile-badge.shared{background:color-mix(in srgb,var(--green) 9%,transparent);color:var(--green)}
.finance-profile-value{position:relative;z-index:1;margin:23px 0 17px}.finance-profile-value>span{display:block;font-size:8px;color:var(--muted)}.finance-profile-value>strong{display:block;font-size:34px;line-height:1.02;letter-spacing:-.045em;margin:5px 0}.finance-profile-value>small{font-size:8px;color:var(--muted)}
.finance-profile-actions{position:relative;z-index:1;display:flex;gap:7px;flex-wrap:wrap}.profile-action{border:1px solid color-mix(in srgb,var(--line) 45%,transparent);background:color-mix(in srgb,var(--surface2) 84%,transparent);color:var(--text);border-radius:12px;min-height:38px;padding:8px 11px;display:inline-flex;align-items:center;justify-content:center;gap:7px;font:inherit;font-size:8px;font-weight:800;cursor:pointer;transition:transform .14s ease,background .16s ease}.profile-action:active{transform:scale(.97)}.profile-action.primary{background:color-mix(in srgb,var(--primary) 12%,var(--surface2));color:var(--primary);border-color:transparent}.finance-profile-shell.couple .profile-action.primary{background:color-mix(in srgb,var(--green) 12%,var(--surface2));color:var(--green)}
.premium-home-section{margin:0 0 14px}.premium-section-title{display:flex;justify-content:space-between;align-items:end;gap:12px;margin:0 1px 10px}.premium-section-title h2{font-size:15px;margin:3px 0 0}.premium-section-title>small{font-size:8px;color:var(--muted);text-align:right}
.premium-summary-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border:1px solid color-mix(in srgb,var(--line) 64%,transparent);background:color-mix(in srgb,var(--surface-solid) 95%,transparent);border-radius:17px;overflow:hidden;margin-bottom:9px;box-shadow:0 5px 18px rgba(0,0,0,.025)}.premium-summary-grid article{padding:11px 12px;min-width:0}.premium-summary-grid article+article{border-left:1px solid color-mix(in srgb,var(--line) 58%,transparent)}.premium-summary-grid small{display:block;font-size:7px;color:var(--muted)}.premium-summary-grid strong{display:block;font-size:13px;margin:4px 0 2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.premium-summary-grid span{display:block;font-size:7px;color:var(--muted)}
.premium-flow-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.premium-flow-card{width:100%;display:grid;grid-template-columns:36px minmax(0,1fr) 14px;align-items:center;gap:9px;text-align:left;border:1px solid color-mix(in srgb,var(--line) 60%,transparent);background:var(--surface-solid);color:var(--text);border-radius:16px;padding:10px 11px;min-height:66px;cursor:pointer;box-shadow:0 5px 17px rgba(0,0,0,.025);transition:transform .14s ease,border-color .16s ease}.premium-flow-card:active{transform:scale(.985)}.premium-flow-icon{width:34px;height:34px;border-radius:11px;display:grid;place-items:center}.premium-flow-card.income .premium-flow-icon{color:var(--green);background:color-mix(in srgb,var(--green) 10%,var(--surface2))}.premium-flow-card.expense .premium-flow-icon{color:var(--coral);background:color-mix(in srgb,var(--coral) 10%,var(--surface2))}.premium-flow-card.pending .premium-flow-icon{color:var(--gold);background:color-mix(in srgb,var(--gold) 10%,var(--surface2))}.premium-flow-card.debt .premium-flow-icon{color:var(--primary);background:color-mix(in srgb,var(--primary) 9%,var(--surface2))}.premium-flow-card small{display:block;font-size:7px;letter-spacing:.12em;color:var(--muted);font-weight:850}.premium-flow-card strong{display:block;font-size:14px;margin:3px 0 1px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.premium-flow-card p{font-size:7.5px;color:var(--muted);margin:0}.premium-flow-card>svg{color:var(--muted)}
.premium-home-lower{gap:9px}.premium-panel{border-color:color-mix(in srgb,var(--line) 58%,transparent)!important;box-shadow:0 7px 22px rgba(0,0,0,.025)!important;background:color-mix(in srgb,var(--surface-solid) 97%,transparent)!important}.premium-empty{border-radius:13px;background:var(--surface2);padding:13px!important}
/* Premium global surfaces */
.panel,.item-card,.debt-card,.goal-card,.sharing-space-row,.share-invite,.report-filter-panel{border-color:color-mix(in srgb,var(--line) 60%,transparent)!important;box-shadow:0 6px 20px rgba(0,0,0,.025)}
.panel{border-radius:18px}.item-card,.debt-card,.goal-card{border-radius:16px!important}.more-card,.setting-row{border-color:color-mix(in srgb,var(--line) 58%,transparent)!important}.modal,.action-sheet{border-radius:24px 24px 0 0!important;box-shadow:0 -18px 50px rgba(0,0,0,.16)!important}.field input,.field select,.field textarea{border-radius:13px!important;border-color:color-mix(in srgb,var(--line) 65%,transparent)!important;background:var(--surface-solid)!important}.btn{border-radius:12px!important}.mini-btn{border-radius:10px!important}.bottom{border-color:color-mix(in srgb,var(--line) 60%,transparent)!important;box-shadow:0 -8px 28px rgba(0,0,0,.08)!important;background:color-mix(in srgb,var(--surface-solid) 92%,transparent)!important;backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
@media(min-width:900px){.main{padding-bottom:34px!important}.finance-profile-shell{max-width:980px}.finance-profile-switch{max-width:460px}.premium-summary-grid{max-width:980px}.premium-flow-grid{grid-template-columns:repeat(4,minmax(0,1fr))}}
@media(max-width:720px){.main{padding-bottom:calc(124px + env(safe-area-inset-bottom,0px))!important}.finance-profile-shell{margin-bottom:19px}.finance-profile-switch{gap:6px}.finance-profile-switch button{min-height:54px;padding:8px 9px}.finance-profile-card{border-radius:21px;padding:15px}.finance-profile-identity h1{font-size:15px}.finance-profile-identity p{font-size:8px}.profile-badge{display:none}.finance-profile-value{margin:19px 0 14px}.finance-profile-value>strong{font-size:30px}.finance-profile-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.finance-profile-actions .profile-action:nth-child(3){grid-column:1/-1}.premium-section-title>small{display:none}.premium-summary-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.premium-summary-grid article{padding:10px 8px}.premium-summary-grid strong{font-size:11px}.premium-summary-grid span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.premium-flow-grid{gap:6px}.premium-flow-card{grid-template-columns:32px minmax(0,1fr) 12px;min-height:61px;padding:9px}.premium-flow-icon{width:31px;height:31px}.premium-flow-card strong{font-size:12px}.premium-home-lower{grid-template-columns:1fr!important}.premium-scope-dock{padding:8px 9px}.premium-scope-copy span:last-child{display:none}.premium-scope-segment button{padding:7px 9px}.bottom{left:14px!important;right:14px!important;bottom:calc(10px + env(safe-area-inset-bottom,0px))!important;width:auto!important}}
@media(max-width:390px){.finance-profile-switch button>i{display:none}.switch-avatar{width:31px;height:31px}.finance-profile-value>strong{font-size:28px}.premium-summary-grid strong{font-size:10px}.premium-flow-card p{display:none}}
@media(prefers-reduced-motion:reduce){.finance-profile-switch button,.profile-action,.premium-flow-card{transition:none!important}}
'''

# Garantias para impedir a regressão visual que motivou este patch.
for marker in ['premium-scope-dock','finance-profile-card','premium-summary-grid','premium-flow-grid']:
    if marker not in a and marker not in css: raise SystemExit('UI premium ausente: '+marker)
if "state.page==='home'" not in a: raise SystemExit('Home ainda pode renderizar seletor duplicado')
if 'profile-page-intro' in a: raise SystemExit('Saudação duplicada antiga ainda presente')

app.write_text(a);cssp.write_text(css)
print('Ritmo V1: perfis Pessoal e Casal reconstruídos com UI premium, sem duplicação ou sobreposição.')
