from pathlib import Path
import sys

root=Path(sys.argv[1])
audit=root/'ci-commercial-audit.mjs'

audit.write_text(r'''import http from 'node:http';
import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';
if(!process.env.CI){console.log('Auditoria comercial reservada ao CI.');process.exit(0)}
const dist=path.join(process.cwd(),'dist'),build=JSON.parse(fs.readFileSync(path.join(dist,'version.json'),'utf8')).build;
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png'};
let currentTheme='dark';
function boot(){return {profile:{id:1,name:'Flavio Neto',username:'flavio.neto',data_version:1},scope:'personal',sharing:{partnership_id:null,active:false,members:[],partner:null,incoming_invites:[],outgoing_invites:[]},settings:{theme:currentTheme,auto_lock_minutes:5,mobile_shortcuts:'["expenses","debts","goals"]',notifications_enabled:1,notify_due:1,notify_overdue:1,notify_goals:1,reminder_days:3,monthly_summary:1,seen_notifications:'[]'},security:{webauthn_count:1},incomes:[],expenses:[],debts:[],debt_events:[],goals:[],goal_contributions:[],server_time:new Date().toISOString()}}
const harness=`<script>(async()=>{const checks=[],errors=[];addEventListener('error',e=>errors.push(String(e.message||e.error||'erro')));addEventListener('unhandledrejection',e=>errors.push(String(e.reason||'rejeicao')));const wait=m=>new Promise(r=>setTimeout(r,m));const ok=(v,m)=>{if(!v)throw new Error(m);checks.push(m)};const root=document.getElementById('root');const overflow=l=>ok(document.documentElement.scrollWidth<=innerWidth+5,'sem overflow '+l);const click=async(sel,label,ms=90)=>{const el=document.querySelector(sel);ok(!!el,'controle '+label);el.click();await wait(ms);overflow(label);return el};const text=s=>root?.innerText?.includes(s);const openMore=async()=>{const m=document.querySelector('[data-page="more"]');if(!m)return false;m.click();await wait(70);return !!document.querySelector('[data-page="settings"]')};const openSettings=async()=>{let s=document.querySelector('[data-page="settings"]');if(s){s.click();await wait(70);return true}if(await openMore()){s=document.querySelector('[data-page="settings"]');if(s){s.click();await wait(70);return true}}return false};try{for(let i=0;i<100&&!document.querySelector('[data-page="home"]');i++)await wait(50);ok(!!document.querySelector('[data-page="home"]'),'aplicativo carregado');ok(!document.querySelector('#authForm'),'sem login intermediario');overflow('inicio');
await click('[data-page="expenses"]','movimentacoes');ok(text('Movimentações')||text('Saídas'),'tela movimentacoes');const expNew=document.querySelector('[data-new="expense"],[data-smart-new="expense"]');if(expNew){expNew.click();await wait(60);ok(!!document.querySelector('.modal-wrap,#modalWrap'),'modal saida');document.querySelector('#modalClose,.modal .close')?.click();await wait(30)}
await click('[data-page="debts"]','dividas');ok(text('Dívidas'),'tela dividas');const debtNew=document.querySelector('[data-new="debt"],[data-smart-new="debt"]');if(debtNew){debtNew.click();await wait(60);ok(!!document.querySelector('.modal-wrap,#modalWrap'),'modal divida');document.querySelector('#modalClose,.modal .close')?.click();await wait(30)}
await click('[data-page="goals"]','metas');ok(text('Metas'),'tela metas');const goalNew=document.querySelector('[data-new="goal"],[data-smart-new="goal"]');if(goalNew){goalNew.click();await wait(60);ok(!!document.querySelector('.modal-wrap,#modalWrap'),'modal meta');document.querySelector('#modalClose,.modal .close')?.click();await wait(30)}
const more=document.querySelector('[data-page="more"]');if(more){more.click();await wait(80);ok(text('Menu'),'menu');overflow('menu');const upd=document.querySelector('[data-system-update]');ok(!!upd,'botao atualizar');upd.click();await wait(900);ok(!upd.disabled&&!upd.classList.contains('updating'),'atualizacao encerra sem loop');for(const [p,label,needle] of [['sharing','compartilhamento','Compartilhamento'],['calendar','calendario','Calendário'],['insights','insights','Insights'],['profile','perfil','Editar perfil']]){ok(await openMore(),'abrir menu '+label);await click('[data-page="'+p+'"]',label);ok(text(needle),'tela '+label)}
for(const [sub,label] of [['personalization','personalizacao'],['notifications','notificacoes'],['security','seguranca']]){ok(await openSettings(),'abrir configuracoes '+label);ok(text('Configurações'),'tela configuracoes '+label);await click('[data-settings="'+sub+'"]',label);ok(root.innerText.trim().length>20,'conteudo '+label);if(sub==='personalization'){const light=document.querySelector('[data-theme="light"]'),dark=document.querySelector('[data-theme="dark"]');ok(!!light&&!!dark,'controles de tema');light.click();await wait(180);ok(!document.documentElement.classList.contains('dark'),'tema claro aplicado');dark.click();await wait(180);ok(document.documentElement.classList.contains('dark'),'tema escuro aplicado');ok(document.querySelectorAll('meta[name="theme-color"]').length===1,'uma meta de tema');ok(document.querySelector('meta[name="theme-color"]').content!=='#F7F5EF','barra escura aplicada');const shortcut=document.querySelector('[data-page="shortcuts"]');if(shortcut){shortcut.click();await wait(80);ok(/atalho/i.test(root.innerText),'atalhos renderizados');overflow('atalhos')}}}
ok(await openMore(),'abrir menu sobre');const about=document.querySelector('[data-settings-open="about"]');if(about){about.click();await wait(80);ok(/Versão|Sobre/i.test(root.innerText),'sobre renderizado')}}else{const values=new Set([...document.querySelectorAll('[data-page]')].map(x=>x.dataset.page).filter(Boolean));ok(values.has('home')&&values.has('expenses')&&values.has('debts')&&values.has('goals'),'navegacao desktop principal');for(const p of ['calendar','insights','settings']){const el=document.querySelector('[data-page="'+p+'"]');if(el){el.click();await wait(70);ok(root.innerText.trim().length>20,'desktop '+p);overflow('desktop '+p)}}}
const bell=document.querySelector('[data-page="notifications"]');if(bell){bell.click();await wait(60);ok(/Avisos|Notifica/i.test(root.innerText),'notificacoes renderizadas')}ok(!/Cloudflare|WebAuthn|Service Worker|\bD1\b|\bKV\b|\bR2\b|ID interno/i.test(root.innerText),'sem termos tecnicos visiveis');ok(errors.length===0,'sem erros globais');document.body.dataset.ciCommercial='pass';document.body.dataset.ciChecks=String(checks.length)}catch(e){document.body.dataset.ciCommercial='fail';document.body.dataset.ciError=String(e.message||e).slice(0,240)}})()</script>`;
const server=http.createServer((req,res)=>{try{const u=new URL(req.url,'http://127.0.0.1');if(u.pathname==='/seed'){res.writeHead(200,{'content-type':'text/html'});res.end(`<script>localStorage.setItem('ritmo:theme','dark');localStorage.setItem('ritmo:saved-account',JSON.stringify({username:'flavio.neto',name:'Flavio Neto',id:'1',bio:true}));localStorage.setItem('ritmo:bio:1:verified','1');sessionStorage.setItem('ritmo:unlock-session:1','1');sessionStorage.setItem('ritmo:unlock-session:1:activity',String(Date.now()));document.cookie='ci=1; path=/';location.replace('/?ci-commercial=1')</script>`);return}if(u.pathname.startsWith('/api/')){if(u.pathname==='/api/bootstrap'){res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(boot()));return}if(u.pathname==='/api/version'){res.writeHead(200,{'content-type':'application/json'});res.end('{"version":1}');return}if(u.pathname==='/api/settings'&&req.method==='PATCH'){let raw='';req.on('data',d=>raw+=d);req.on('end',()=>{try{const b=JSON.parse(raw||'{}');if(['light','dark','system'].includes(b.theme))currentTheme=b.theme}catch{}res.writeHead(200,{'content-type':'application/json'});res.end('{"ok":true}')});return}res.writeHead(200,{'content-type':'application/json'});res.end('{"ok":true}');return}let rel=u.pathname==='/'?'index.html':u.pathname.replace(/^\/+/,''),file=path.join(dist,rel);if(!file.startsWith(dist)||!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(dist,'index.html');let body=fs.readFileSync(file);if(path.basename(file)==='index.html'&&u.searchParams.has('ci-commercial'))body=Buffer.from(body.toString().replace('</body>',harness+'</body>'));res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream','cache-control':'no-store'});res.end(body)}catch(e){res.writeHead(500);res.end(String(e))}});
await new Promise((r,j)=>server.listen(4174,'127.0.0.1',e=>e?j(e):r()));const browser=['/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser'].find(fs.existsSync);if(!browser){server.close();throw new Error('Chrome/Chromium ausente')}
async function run(size){currentTheme='dark';const args=['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--window-size='+size,'--virtual-time-budget=10000','--user-data-dir=/tmp/ritmo-commercial-'+Date.now()+'-'+Math.random(),'--dump-dom','http://127.0.0.1:4174/seed'];const c=spawn(browser,args,{stdio:['ignore','pipe','pipe']});let o='',e='';c.stdout.on('data',d=>o+=d);c.stderr.on('data',d=>e+=d);const t=setTimeout(()=>c.kill('SIGKILL'),26000),code=await new Promise(r=>c.on('close',r));clearTimeout(t);if(code!==0)throw new Error(e.slice(-1400));if(!/data-ci-commercial="pass"/.test(o)){const m=o.match(/data-ci-error="([^"]*)"/);throw new Error('Auditoria '+size+' falhou: '+(m?.[1]||o.slice(-2200)))}return o}
await run('390,844');await run('1440,900');await new Promise(r=>server.close(r));console.log('Auditoria comercial aprovada pela interface real: navegação, temas, modais, atualização, mobile e desktop. Build '+build);''')
print('Ritmo V1: auditoria comercial pela interface real com navegação completa aplicada.')
