import type { BootstrapData, Debt } from '../domain/types'
import { money, shortDate } from '../lib/format'
import { Icon } from '../ui/Icon'

function dueState(debt:Debt,cutoff:string){const balance=Number(debt.balance??debt.total_amount??0);if(balance<=0)return {label:'Quitada',tone:'success'};if(debt.due_date&&debt.due_date<cutoff)return {label:'Vencida',tone:'danger'};if(debt.due_date===cutoff)return {label:'Vence hoje',tone:'warning'};if(debt.due_date)return {label:'A vencer',tone:'muted'};return {label:'Ativa',tone:'muted'}}

export function DebtsPage({data,onNew,onEdit,onDelete,onEvent}:{data:BootstrapData;onNew:()=>void;onEdit:(debt:Debt)=>void;onDelete:(debt:Debt)=>void;onEvent:(debt:Debt,kind:'payment'|'credit')=>void}){
  const total=data.debts.reduce((sum,debt)=>sum+Number(debt.balance??debt.total_amount??0),0),cutoff=(data.server_time||new Date().toISOString()).slice(0,10)
  return <div className="page-stack">
    <header className="page-header ios-page-header"><div><small>DÍVIDAS</small><h1>Compromissos sob controle</h1><p>Pagamento e Haver ficam no histórico da dívida e só mexem no saldo quando realmente acontecem.</p></div><button className="primary-button" type="button" onClick={onNew}><Icon name="plus"/> Nova dívida</button></header>
    <section className="debt-total-card"><span><Icon name="debt"/></span><div><small>SALDO DEVEDOR</small><strong>{money(total)}</strong><p>{data.debts.filter(d=>Number(d.balance??d.total_amount)>0).length} dívida(s) aberta(s)</p></div></section>
    <div className="cards-grid">{data.debts.length?data.debts.map(debt=>{const balance=Number(debt.balance??debt.total_amount??0),paid=Number(debt.paid_amount??Math.max(0,debt.total_amount-balance)),progress=debt.total_amount>0?Math.min(100,Math.max(0,paid/debt.total_amount*100)):0,state=dueState(debt,cutoff),events=(data.debt_events||[]).filter(e=>e.debt_id===debt.id).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4);return <article className="premium-card debt-card debt-card-rich" key={debt.id}>
      <div className="card-top"><span className="card-icon"><Icon name="debt"/></span><div className="card-heading"><small><em className={`debt-state ${state.tone}`}>{state.label}</em></small><h2>{debt.creditor}</h2><p>{debt.due_date?`Vencimento ${shortDate(debt.due_date)}`:'Sem vencimento definido'}</p></div><div className="card-actions"><button type="button" onClick={()=>onEdit(debt)} aria-label="Editar"><Icon name="edit"/></button><button type="button" onClick={()=>onDelete(debt)} aria-label="Excluir"><Icon name="trash"/></button></div></div>
      <div className="debt-values"><span><small>Saldo</small><strong>{money(balance)}</strong></span><span><small>Abatido</small><strong>{money(paid)}</strong></span><span><small>Total</small><strong>{money(debt.total_amount)}</strong></span></div><div className="progress-track"><span style={{width:`${progress}%`}}/></div>
      {events.length>0&&<div className="debt-event-history"><div className="mini-section-title"><strong>Histórico recente</strong><small>Pagamento e Haver</small></div>{events.map(event=><div className="debt-event-row" key={event.id}><span className={event.kind==='pagamento'?'event-icon payment':'event-icon credit'}><Icon name={event.kind==='pagamento'?'check':'transfer'}/></span><span><strong>{event.kind==='pagamento'?'Pagamento':'Haver'}</strong><small>{shortDate(event.date)}{event.created_by_name?` · ${event.created_by_name.split(' ')[0]}`:''}</small></span><b>{money(event.amount)}</b></div>)}</div>}
      {balance>0&&<div className="card-footer-actions"><button type="button" onClick={()=>onEvent(debt,'payment')}><Icon name="check"/> Pagamento</button><button type="button" onClick={()=>onEvent(debt,'credit')}><Icon name="transfer"/> Haver</button></div>}
    </article>}):<div className="premium-card empty-card">Nenhuma dívida cadastrada neste perfil.</div>}</div>
  </div>
}
