import { audit, cents, dateValue, ensureWorkspaceAccess, error, idempotentExisting, json, MAX_FILE, normalizeText, normalizeUsername, readJson, resolveWorkspace, type Env, type SessionUser } from './utils'

export async function bootstrap(request:Request,env:Env,user:SessionUser){
  const url=new URL(request.url),{workspaces,active}=await resolveWorkspace(env,user.id,url.searchParams.get('workspace'))
  const [transactions,goals,debts,settings,passkeys]=await Promise.all([
    env.DB.prepare('SELECT * FROM transactions WHERE workspace_id=? ORDER BY date DESC,created_at DESC LIMIT 250').bind(active.id).all(),
    env.DB.prepare('SELECT * FROM goals WHERE workspace_id=? ORDER BY created_at DESC LIMIT 100').bind(active.id).all(),
    env.DB.prepare("SELECT * FROM debts WHERE workspace_id=? ORDER BY CASE status WHEN 'active' THEN 0 ELSE 1 END,due_date,created_at DESC LIMIT 100").bind(active.id).all(),
    env.DB.prepare('SELECT theme,language FROM settings WHERE user_id=?').bind(user.id).first<{theme:'light'|'dark'|'system';language:'pt-BR'}>(),
    env.DB.prepare('SELECT COUNT(*) AS total FROM webauthn_credentials WHERE user_id=?').bind(user.id).first<{total:number}>(),
  ])
  return json({profile:user,workspaces,active_workspace:active,transactions:transactions.results||[],goals:goals.results||[],debts:debts.results||[],settings:settings||{theme:'system',language:'pt-BR'},passkeys:Number(passkeys?.total||0),server_time:new Date().toISOString()})
}

export async function routeTransactions(request:Request,env:Env,user:SessionUser,pathname:string){
  const match=pathname.match(/^\/api\/transactions(?:\/([^/]+))?$/);if(!match)return null;const id=match[1]
  if(request.method==='POST'&&!id){const body=await readJson<any>(request),workspaceId=String(body.workspace_id||'');await ensureWorkspaceAccess(env,user.id,workspaceId);const operationId=request.headers.get('x-operation-id'),existing=await idempotentExisting(env,'transactions',operationId);if(existing)return json(existing)
    const row={id:crypto.randomUUID(),type:body.type==='income'?'income':'expense',description:normalizeText(body.description,100),category:normalizeText(body.category,50)||'Outros',amount:cents(body.amount_cents),date:dateValue(body.date),dueDate:body.due_date?dateValue(body.due_date):null,status:body.status==='pending'?'pending':'paid',notes:normalizeText(body.notes,500)||null};if(!row.description||row.amount<=0)return error('Descrição e valor são obrigatórios.')
    await env.DB.prepare('INSERT INTO transactions(id,workspace_id,user_id,type,description,category,amount_cents,date,due_date,status,notes,operation_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(row.id,workspaceId,user.id,row.type,row.description,row.category,row.amount,row.date,row.dueDate,row.status,row.notes,operationId).run();await audit(env,user.id,workspaceId,'transaction.create','transaction',row.id);return json(await env.DB.prepare('SELECT * FROM transactions WHERE id=?').bind(row.id).first(),201)}
  if(!id)return error('Rota inválida.',405);const current=await env.DB.prepare('SELECT * FROM transactions WHERE id=?').bind(id).first<any>();if(!current)return error('Movimentação não encontrada.',404);await ensureWorkspaceAccess(env,user.id,current.workspace_id);const expected=request.headers.get('x-entity-version');if(expected&&Number(expected)!==Number(current.version))return error('Este lançamento foi alterado em outro dispositivo. Atualize e tente novamente.',409)
  if(request.method==='DELETE'){await env.DB.prepare('DELETE FROM transactions WHERE id=?').bind(id).run();await audit(env,user.id,current.workspace_id,'transaction.delete','transaction',id);return json({ok:true})}
  if(request.method==='PATCH'){const body=await readJson<any>(request),description=normalizeText(body.description??current.description,100),category=normalizeText(body.category??current.category,50)||'Outros',amount=body.amount_cents==null?current.amount_cents:cents(body.amount_cents),date=body.date?dateValue(body.date):current.date,dueDate=body.due_date===''?null:(body.due_date?dateValue(body.due_date):current.due_date),status=body.status==='pending'?'pending':(body.status==='paid'?'paid':current.status);await env.DB.prepare('UPDATE transactions SET description=?,category=?,amount_cents=?,date=?,due_date=?,status=?,notes=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(description,category,amount,date,dueDate,status,normalizeText(body.notes??current.notes,500)||null,id).run();await audit(env,user.id,current.workspace_id,'transaction.update','transaction',id);return json(await env.DB.prepare('SELECT * FROM transactions WHERE id=?').bind(id).first())}
  return error('Método não permitido.',405)
}

export async function routeGoals(request:Request,env:Env,user:SessionUser,pathname:string){
  const match=pathname.match(/^\/api\/goals(?:\/([^/]+))?$/);if(!match)return null;const id=match[1]
  if(request.method==='POST'&&!id){const body=await readJson<any>(request),workspaceId=String(body.workspace_id||'');await ensureWorkspaceAccess(env,user.id,workspaceId);const operationId=request.headers.get('x-operation-id'),existing=await idempotentExisting(env,'goals',operationId);if(existing)return json(existing);const goalId=crypto.randomUUID(),title=normalizeText(body.title,100),target=cents(body.target_cents),current=cents(body.current_cents);if(!title||target<=0)return error('Título e valor da meta são obrigatórios.');await env.DB.prepare('INSERT INTO goals(id,workspace_id,user_id,title,target_cents,current_cents,deadline,icon,operation_id) VALUES(?,?,?,?,?,?,?,?,?)').bind(goalId,workspaceId,user.id,title,target,Math.min(current,target),body.deadline?dateValue(body.deadline):null,normalizeText(body.icon,30)||'target',operationId).run();await audit(env,user.id,workspaceId,'goal.create','goal',goalId);return json(await env.DB.prepare('SELECT * FROM goals WHERE id=?').bind(goalId).first(),201)}
  if(!id)return error('Rota inválida.',405);const current=await env.DB.prepare('SELECT * FROM goals WHERE id=?').bind(id).first<any>();if(!current)return error('Meta não encontrada.',404);await ensureWorkspaceAccess(env,user.id,current.workspace_id)
  if(request.method==='DELETE'){await env.DB.prepare('DELETE FROM goals WHERE id=?').bind(id).run();await audit(env,user.id,current.workspace_id,'goal.delete','goal',id);return json({ok:true})}
  if(request.method==='PATCH'){const body=await readJson<any>(request),expected=request.headers.get('x-entity-version');if(expected&&Number(expected)!==Number(current.version))return error('Esta meta foi alterada em outro dispositivo.',409);const target=body.target_cents==null?current.target_cents:cents(body.target_cents),saved=body.current_cents==null?current.current_cents:cents(body.current_cents);await env.DB.prepare('UPDATE goals SET title=?,target_cents=?,current_cents=?,deadline=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(normalizeText(body.title??current.title,100),target,Math.min(saved,target),body.deadline===''?null:(body.deadline?dateValue(body.deadline):current.deadline),id).run();await audit(env,user.id,current.workspace_id,'goal.update','goal',id);return json(await env.DB.prepare('SELECT * FROM goals WHERE id=?').bind(id).first())}
  return error('Método não permitido.',405)
}

export async function routeDebts(request:Request,env:Env,user:SessionUser,pathname:string){
  const match=pathname.match(/^\/api\/debts(?:\/([^/]+))?$/);if(!match)return null;const id=match[1]
  if(request.method==='POST'&&!id){const body=await readJson<any>(request),workspaceId=String(body.workspace_id||'');await ensureWorkspaceAccess(env,user.id,workspaceId);const operationId=request.headers.get('x-operation-id'),existing=await idempotentExisting(env,'debts',operationId);if(existing)return json(existing);const debtId=crypto.randomUUID(),title=normalizeText(body.title,100),total=cents(body.total_cents),paid=cents(body.paid_cents);if(!title||total<=0)return error('Título e valor da dívida são obrigatórios.');await env.DB.prepare('INSERT INTO debts(id,workspace_id,user_id,title,creditor,total_cents,paid_cents,due_date,status,operation_id) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(debtId,workspaceId,user.id,title,normalizeText(body.creditor,80),total,Math.min(paid,total),body.due_date?dateValue(body.due_date):null,paid>=total?'paid':'active',operationId).run();await audit(env,user.id,workspaceId,'debt.create','debt',debtId);return json(await env.DB.prepare('SELECT * FROM debts WHERE id=?').bind(debtId).first(),201)}
  if(!id)return error('Rota inválida.',405);const current=await env.DB.prepare('SELECT * FROM debts WHERE id=?').bind(id).first<any>();if(!current)return error('Dívida não encontrada.',404);await ensureWorkspaceAccess(env,user.id,current.workspace_id)
  if(request.method==='DELETE'){await env.DB.prepare('DELETE FROM debts WHERE id=?').bind(id).run();await audit(env,user.id,current.workspace_id,'debt.delete','debt',id);return json({ok:true})}
  if(request.method==='PATCH'){const body=await readJson<any>(request),expected=request.headers.get('x-entity-version');if(expected&&Number(expected)!==Number(current.version))return error('Esta dívida foi alterada em outro dispositivo.',409);const total=body.total_cents==null?current.total_cents:cents(body.total_cents),paid=body.paid_cents==null?current.paid_cents:cents(body.paid_cents);await env.DB.prepare('UPDATE debts SET title=?,creditor=?,total_cents=?,paid_cents=?,due_date=?,status=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(normalizeText(body.title??current.title,100),normalizeText(body.creditor??current.creditor,80),total,Math.min(paid,total),body.due_date===''?null:(body.due_date?dateValue(body.due_date):current.due_date),paid>=total?'paid':'active',id).run();await audit(env,user.id,current.workspace_id,'debt.update','debt',id);return json(await env.DB.prepare('SELECT * FROM debts WHERE id=?').bind(id).first())}
  return error('Método não permitido.',405)
}

export async function routeProfile(request:Request,env:Env,user:SessionUser,pathname:string){
  if(pathname==='/api/profile'&&request.method==='PATCH'){const body=await readJson<{display_name?:string;username?:string}>(request),display=normalizeText(body.display_name??user.display_name,60),username=normalizeUsername(body.username??user.username);if(display.length<2||username.length<3)return error('Nome e usuário inválidos.');if(await env.DB.prepare('SELECT id FROM users WHERE username=? AND id<>?').bind(username,user.id).first())return error('Este usuário já está em uso.',409);await env.DB.prepare('UPDATE users SET display_name=?,username=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(display,username,user.id).run();await audit(env,user.id,null,'profile.update','user',user.id);return json({ok:true})}
  if(pathname==='/api/profile/avatar'&&request.method==='PUT'){const contentType=request.headers.get('content-type')||'application/octet-stream',size=Number(request.headers.get('content-length')||0);if(size>MAX_FILE)return error('A imagem deve ter no máximo 2 MB.',413);if(!contentType.startsWith('image/'))return error('Envie uma imagem válida.',415);const body=await request.arrayBuffer();if(body.byteLength>MAX_FILE)return error('A imagem deve ter no máximo 2 MB.',413);const key=`avatars/${user.id}/${crypto.randomUUID()}`;await env.R2.put(key,body,{httpMetadata:{contentType,cacheControl:'private, max-age=3600'}});if(user.avatar_key)await env.R2.delete(user.avatar_key).catch(()=>undefined);await env.DB.prepare('UPDATE users SET avatar_key=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(key,user.id).run();await audit(env,user.id,null,'profile.avatar','user',user.id);return json({ok:true})}
  if(pathname==='/api/profile/avatar'&&request.method==='GET'){const current=await env.DB.prepare('SELECT avatar_key FROM users WHERE id=?').bind(user.id).first<{avatar_key:string|null}>();if(!current?.avatar_key)return new Response(null,{status:404});const object=await env.R2.get(current.avatar_key);if(!object)return new Response(null,{status:404});const headers=new Headers();object.writeHttpMetadata(headers);headers.set('etag',object.httpEtag);headers.set('cache-control','private, max-age=3600');return new Response(object.body,{headers})}
  if(pathname==='/api/settings'&&request.method==='PATCH'){const body=await readJson<{theme?:string}>(request),theme=['light','dark','system'].includes(String(body.theme))?String(body.theme):'system';await env.DB.prepare("INSERT INTO settings(user_id,theme,language,updated_at) VALUES(?,?,'pt-BR',CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET theme=excluded.theme,updated_at=CURRENT_TIMESTAMP").bind(user.id,theme).run();return json({ok:true,theme})}
  return null
}
