import type {Bootstrap,Scope} from './types'
import {cacheGet,cacheSet,outboxAdd,outboxAll,outboxDelete} from './db'
export class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const res=await fetch(path,{...init,headers:{'Content-Type':'application/json','X-Ritmo-Client':'pwa-v2','X-Ritmo-Scope':(localStorage.getItem('ritmo:scope')==='couple'?'couple':'personal'),...(init.headers||{})},credentials:'include'});const data=await res.json().catch(()=>({}));if(!res.ok)throw new ApiError(res.status,data?.error||'Não foi possível concluir.');return data as T}
export async function login(email:string,password:string){return request('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})})}
export async function register(name:string,email:string,password:string){return request('/api/auth/register',{method:'POST',body:JSON.stringify({name,email,password})})}
export async function logout(){return request('/api/auth/logout',{method:'POST',body:'{}'})}
export async function loadBootstrap(scope:Scope,force=false):Promise<Bootstrap>{const key=`bootstrap:${scope}`;if(!force){const cached=await cacheGet<{data:Bootstrap;savedAt:number}>(key);if(cached&&Date.now()-cached.savedAt<90_000)return cached.data}try{const data=await request<Bootstrap>(`/api/bootstrap?scope=${scope}`);await cacheSet(key,{data,savedAt:Date.now()});return data}catch(err){const cached=await cacheGet<{data:Bootstrap;savedAt:number}>(key);if(cached)return cached.data;throw err}}
export async function invalidate(scope?:Scope){if(scope)await cacheSet(`bootstrap:${scope}`,null);else{await cacheSet('bootstrap:personal',null);await cacheSet('bootstrap:couple',null)}}
export async function mutate(path:string,method:'POST'|'PATCH'|'DELETE',body?:unknown){if(!navigator.onLine){const id=crypto.randomUUID();await outboxAdd({id,path,method,body,createdAt:Date.now()});return {queued:true}}await request(path,{method,body:body===undefined?undefined:JSON.stringify(body),headers:{'Idempotency-Key':crypto.randomUUID()}});return {queued:false}}
export async function patch(path:string,body:unknown){return request(path,{method:'PATCH',body:JSON.stringify(body)})}
export async function uploadAvatar(blob:Blob){const res=await fetch('/api/avatar',{method:'PUT',body:blob,credentials:'include',headers:{'Content-Type':'image/webp'}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new ApiError(res.status,data?.error||'Não foi possível enviar a foto.');return data}
export async function flushOutbox(){if(!navigator.onLine)return;for(const item of await outboxAll()){try{await request(item.path,{method:item.method,body:item.body===undefined?undefined:JSON.stringify(item.body),headers:{'Idempotency-Key':item.id}});await outboxDelete(item.id)}catch(err){if(err instanceof ApiError&&err.status<500)await outboxDelete(item.id);else break}}window.dispatchEvent(new Event('ritmo:synced'))}
export function installSync(){const fn=()=>void flushOutbox();window.addEventListener('online',fn);void flushOutbox();return()=>window.removeEventListener('online',fn)}
