const DB_NAME='ritmo-v2-local',VER=1
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,VER);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('cache'))db.createObjectStore('cache');if(!db.objectStoreNames.contains('outbox'))db.createObjectStore('outbox',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export async function cacheGet<T>(key:string):Promise<T|null>{const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction('cache','readonly'),r=tx.objectStore('cache').get(key);r.onsuccess=()=>resolve(r.result??null);r.onerror=()=>reject(r.error)})}
export async function cacheSet(key:string,value:unknown){const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('cache','readwrite');tx.objectStore('cache').put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export interface OutboxItem{id:string;path:string;method:string;body?:unknown;createdAt:number}
export async function outboxAdd(item:OutboxItem){const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('outbox','readwrite');tx.objectStore('outbox').put(item);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function outboxAll():Promise<OutboxItem[]>{const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction('outbox','readonly'),r=tx.objectStore('outbox').getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
export async function outboxDelete(id:string){const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('outbox','readwrite');tx.objectStore('outbox').delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function clearLocal(){const db=await openDb();for(const name of ['cache','outbox'])await new Promise<void>((resolve,reject)=>{const tx=db.transaction(name,'readwrite');tx.objectStore(name).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
