import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Activity, ArrowDownRight, ArrowUpRight, BarChart3, Bell, CalendarDays, ChevronRight, CreditCard, Goal, Home, Landmark, LogOut, Plus, ReceiptText, Search, ShieldCheck, Target, TrendingUp, UserRound, Users, WalletCards, X } from 'lucide-react'
import { api, authStore } from './lib/api'
import Modal from './components/Modal'
import Skeleton from './components/Skeleton'
import Toasts, { ToastData } from './components/Toast'

type Me={id:string;name:string;email:string;role:'OWNER'|'GUEST';tenant_id:string}
type Tx={id:string;type:'INCOME'|'EXPENSE';description:string;amount_cents:number;status:'PENDING'|'PAID'|'OVERDUE';due_date?:string;category?:string;created_at:string}
type GoalT={id:string;name:string;target_cents:number;current_cents:number;deadline?:string}
type Debt={id:string;name:string;total_cents:number;remaining_cents:number;due_date?:string}
type Summary={income_cents:number;expense_cents:number;pending_cents:number;balance_cents:number;reserve_cents:number}
const brl=(c=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100)
const nav=[['home','Início',Home],['transactions','Extrato',ReceiptText],['goals','Metas',Target],['reserve','Reserva',Landmark],['debts','Dívidas',CreditCard],['calendar','Agenda',CalendarDays],['reports','Análise',BarChart3],['settings','Perfil',UserRound]] as const

function Brand({compact=false}:{compact?:boolean}){return <img className={compact?'brand compact':'brand'} src="/control-logo-gold.svg" alt="CONTROL — Seu dinheiro, mais possibilidades"/>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function Progress({label,value}:{label:string;value:number}){return <div className="progress"><div><b>{label}</b><span>{value}%</span></div><i><em style={{width:`${value}%`}}/></i></div>}
function PageHead({title,subtitle,action,label='Adicionar'}:{title:string;subtitle:string;action?:()=>void;label?:string}){return <div className="page-head"><div><span>CONTROL</span><h1>{title}</h1><p>{subtitle}</p></div>{action&&<button className="primary" onClick={action}><Plus size={18}/>{label}</button>}</div>}

function Auth({onReady}:{onReady:(m:Me)=>void}){
 const [mode,setMode]=useState<'login'|'register'|'invite'>('login'),[busy,setBusy]=useState(false),[err,setErr]=useState('')
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setErr('');const body=Object.fromEntries(new FormData(e.currentTarget));try{const ep=mode==='invite'?'/api/auth/invite':`/api/auth/${mode==='register'?'register':'login'}`;const r=await api<any>(ep,{method:'POST',body:JSON.stringify(body)});authStore.set(r.token);onReady(r.user)}catch(x:any){setErr(x.message)}finally{setBusy(false)}}
 return <main className="auth"><section className="auth-hero"><Brand/><div><span>FINANÇAS INTELIGENTES</span><h1>Seu dinheiro.<br/>Mais possibilidades.</h1><p>Organize, acompanhe e planeje sua vida financeira em um só lugar.</p></div></section><section className="auth-panel"><div className="auth-card"><div className="mobile-brand"><Brand/></div><span className="eyebrow">CONTROL</span><h2>{mode==='register'?'Criar conta':mode==='invite'?'Acessar convite':'Bem-vindo de volta'}</h2><p className="muted">{mode==='register'?'Comece a organizar suas finanças.':mode==='invite'?'Use o código enviado pelo titular.':'Entre para acessar seu painel financeiro.'}</p>{err&&<div className="error">{err}</div>}<form className="form" onSubmit={submit}>{mode==='register'&&<><label>Nome<input className="field" name="name" required/></label><label>Nome da conta<input className="field" name="tenantName" placeholder="Opcional"/></label></>}{mode==='invite'&&<><label>Código do convite<input className="field" name="code" required/></label><label>Nome<input className="field" name="name" required/></label></>}<label>E-mail<input className="field" name="email" type="email" autoComplete="email" required/></label><label>Senha<input className="field" name="password" type="password" minLength={6} autoComplete={mode==='login'?'current-password':'new-password'} required/></label><button className="primary full" disabled={busy}>{busy?'Aguarde...':mode==='login'?'Entrar':mode==='register'?'Criar conta':'Aceitar convite'}</button></form><div className="auth-actions">{mode!=='login'?<button className="secondary" onClick={()=>setMode('login')}>Voltar ao login</button>:<><button className="secondary" onClick={()=>setMode('register')}>Primeiro acesso</button><button className="secondary" onClick={()=>setMode('invite')}>Tenho convite</button></>}</div><div className="security"><ShieldCheck size={16}/> Conexão segura • dados isolados por conta</div></div></section></main>
}

const tones={blue:['metric blue',WalletCards],green:['metric green',TrendingUp],red:['metric red',ArrowDownRight],gold:['metric gold',CalendarDays]} as const
function Metric({title,value,tone}:{title:string;value:string;tone:keyof typeof tones}){const [cls,I]=tones[tone];return <motion.article whileHover={{y:-2}} className={cls}><div className="metric-icon"><I size={20}/></div><div><span>{title}</span><strong>{value}</strong></div></motion.article>}
function Chart({txs}:{txs:Tx[]}){const data=useMemo(()=>{const now=new Date(),a=[] as {k:string,l:string,v:number}[];for(let i=11;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);a.push({k:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,l:d.toLocaleDateString('pt-BR',{month:'short'}).replace('.',''),v:0})}const m=new Map(a.map((x,i)=>[x.k,i]));for(const t of txs){if(t.status!=='PAID')continue;const raw=t.due_date||t.created_at?.slice(0,10),i=raw?m.get(raw.slice(0,7)):undefined;if(i!==undefined)a[i].v+=t.type==='INCOME'?t.amount_cents:-t.amount_cents}let acc=0;return a.map(x=>({...x,v:acc+=x.v}))},[txs]);const vals=data.map(x=>x.v),mi=Math.min(0,...vals),ma=Math.max(1,...vals),r=Math.max(1,ma-mi),pts=data.map((d,i)=>({x:i/11*100,y:34-(d.v-mi)/r*28})),line=pts.map((p,i)=>`${i?'L':'M'} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(' ');return <section className="surface chart"><div className="section-head"><div><h3>Evolução do saldo</h3><p>Últimos 12 meses • dados reais</p></div><span>{new Date().getFullYear()}</span></div><svg viewBox="0 0 100 36" preserveAspectRatio="none"><defs><linearGradient id="a" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2f8cff" stopOpacity=".45"/><stop offset="1" stopColor="#2f8cff" stopOpacity="0"/></linearGradient></defs>{[8,15,22,29].map(y=><line key={y} x1="0" x2="100" y1={y} y2={y}/>) }<path d={`${line} L100 36 L0 36 Z`} fill="url(#a)"/><path d={line} className="line"/></svg><div className="months">{data.map(x=><span key={x.k}>{x.l}</span>)}</div></section>}
function TxRow({t,onEdit,onDelete}:{t:Tx;onEdit?:()=>void;onDelete?:()=>void}){return <div className="tx"><div className={t.type==='INCOME'?'tx-icon in':'tx-icon out'}>{t.type==='INCOME'?<ArrowUpRight size={18}/>:<ArrowDownRight size={18}/>}</div><button className="tx-main" onClick={onEdit} disabled={!onEdit}><b>{t.description}</b><small>{t.category||'Transação'} · {t.due_date?new Date(t.due_date+'T12:00').toLocaleDateString('pt-BR'):new Date(t.created_at).toLocaleDateString('pt-BR')}</small></button><div className="tx-value"><b className={t.type==='INCOME'?'pos':'neg'}>{t.type==='INCOME'?'+':'-'} {brl(t.amount_cents)}</b><small>{t.status==='PAID'?'Pago':t.status==='PENDING'?'Pendente':'Vencido'}</small></div>{onDelete&&<button className="icon danger" onClick={onDelete}><X size={16}/></button>}</div>}

function Dashboard({me,s,txs,setPage,onNew}:{me:Me;s:Summary;txs:Tx[];setPage:(x:string)=>void;onNew:()=>void}){return <div className="stack"><div className="intro"><div><span>VISÃO GERAL</span><h1>Olá, {me.name.split(' ')[0]}</h1><p>Acompanhe suas finanças em um só lugar.</p></div><button className="primary desktop-only" onClick={onNew}><Plus size={18}/> Novo lançamento</button></div><div className="metrics"><Metric title="Saldo Atual (R$)" value={brl(s.balance_cents)} tone="blue"/><Metric title="Entradas" value={brl(s.income_cents)} tone="green"/><Metric title="Saídas" value={brl(s.expense_cents)} tone="red"/><Metric title="Pendentes" value={brl(s.pending_cents)} tone="gold"/></div><Chart txs={txs}/><div className="dashboard-lower"><section className="surface panel"><div className="section-head"><div><h3>Histórico de transações</h3><p>Movimentações mais recentes</p></div><button className="link" onClick={()=>setPage('transactions')}>Ver todas <ChevronRight size={15}/></button></div>{txs.length?txs.slice(0,6).map(t=><TxRow key={t.id} t={t}/>):<Empty text="Nenhum lançamento ainda."/>}</section><aside className="surface panel quick"><div className="section-head"><div><h3>Resumo rápido</h3><p>Indicadores atuais</p></div><Activity size={20}/></div><div className="reserve-mini"><span>Reserva de emergência</span><b>{brl(s.reserve_cents)}</b></div><Progress label="Comprometimento" value={s.income_cents?Math.min(100,Math.round(s.expense_cents/s.income_cents*100)):0}/><Progress label="Pendências" value={s.expense_cents?Math.min(100,Math.round(s.pending_cents/Math.max(1,s.expense_cents)*100)):0}/></aside></div></div>}
function Transactions({items,onNew,onEdit,onDelete}:{items:Tx[];onNew:()=>void;onEdit:(t:Tx)=>void;onDelete:(id:string)=>void}){const [type,setType]=useState('ALL'),[status,setStatus]=useState('ALL'),[q,setQ]=useState('');const list=items.filter(t=>(type==='ALL'||t.type===type)&&(status==='ALL'||t.status===status)&&(!q||`${t.description} ${t.category||''}`.toLowerCase().includes(q.toLowerCase())));return <><PageHead title="Extrato" subtitle="Entradas, saídas, vencimentos e pagamentos." action={onNew} label="Lançar"/><div className="surface filters"><div><Search size={17}/><input placeholder="Buscar transação" value={q} onChange={e=>setQ(e.target.value)}/></div><select value={type} onChange={e=>setType(e.target.value)}><option value="ALL">Todas</option><option value="INCOME">Entradas</option><option value="EXPENSE">Saídas</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Todos os status</option><option value="PAID">Pago</option><option value="PENDING">Pendente</option><option value="OVERDUE">Vencido</option></select></div><section className="surface panel">{list.length?list.map(t=><TxRow key={t.id} t={t} onEdit={()=>onEdit(t)} onDelete={()=>onDelete(t.id)}/>):<Empty text="Nenhum lançamento encontrado."/>}</section></>}
function Goals({items,onNew,onEdit}:{items:GoalT[];onNew:()=>void;onEdit:(g:GoalT)=>void}){return <><PageHead title="Metas" subtitle="Planeje objetivos e acompanhe seu progresso." action={onNew}/><div className="cards">{items.length?items.map(g=>{const p=Math.min(100,Math.round(g.current_cents/g.target_cents*100));return <button key={g.id} className="surface goal" onClick={()=>onEdit(g)}><div><Goal/><b>{p}%</b></div><h3>{g.name}</h3><p>{brl(g.current_cents)} de {brl(g.target_cents)}</p><Progress label="Progresso" value={p}/></button>}):<div className="surface"><Empty text="Crie sua primeira meta."/></div>}</div></>}
function Reserve({s,onMove}:{s:Summary;onMove:()=>void}){return <><PageHead title="Reserva de emergência" subtitle="Um saldo separado para proteger seus planos." action={onMove} label="Movimentar"/><section className="surface reserve"><div><Landmark/><span>SALDO RESERVADO</span><strong>{brl(s.reserve_cents)}</strong></div><p>Os aportes e retiradas ficam separados dos lançamentos comuns para não misturar reserva com o fluxo mensal.</p></section></>}
function Debts({items,onNew,onPay}:{items:Debt[];onNew:()=>void;onPay:(d:Debt)=>void}){return <><PageHead title="Dívidas" subtitle="Acompanhe o saldo devedor e registre abatimentos." action={onNew}/><div className="cards two">{items.length?items.map(d=>{const p=d.total_cents?Math.round((d.total_cents-d.remaining_cents)/d.total_cents*100):0;return <section key={d.id} className="surface debt"><div><CreditCard/><span><b>{d.name}</b><small>Restante {brl(d.remaining_cents)}</small></span><strong>{p}%</strong></div><Progress label="Quitado" value={p}/>{d.remaining_cents>0&&<button className="secondary full" onClick={()=>onPay(d)}>Registrar pagamento / haver</button>}</section>}):<div className="surface"><Empty text="Nenhuma dívida cadastrada."/></div>}</div></>}
function CalendarPage({txs}:{txs:Tx[]}){const a=txs.filter(t=>t.due_date).sort((x,y)=>(x.due_date||'').localeCompare(y.due_date||''));return <><PageHead title="Agenda financeira" subtitle="Vencimentos e compromissos organizados por data."/><section className="surface panel">{a.length?a.map(t=><div className="agenda" key={t.id}><span>{new Date((t.due_date||'')+'T12:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</span><div><b>{t.description}</b><small>{t.status==='PAID'?'Pago':t.status==='PENDING'?'Pendente':'Vencido'} · {brl(t.amount_cents)}</small></div></div>):<Empty text="Adicione datas de vencimento aos lançamentos para vê-los aqui."/>}</section></>}
function Reports({s,txs}:{s:Summary;txs:Tx[]}){return <><PageHead title="Análise" subtitle="Resumo financeiro pronto para consultar ou salvar em PDF."/><section className="surface report"><div className="report-head"><img src="/control-symbol-gold.svg"/><img src="/control-logo-gold.svg"/><button className="primary no-print" onClick={()=>window.print()}>Imprimir / PDF</button></div><div className="report-metrics"><span>Entradas<b>{brl(s.income_cents)}</b></span><span>Saídas<b>{brl(s.expense_cents)}</b></span><span>Pendentes<b>{brl(s.pending_cents)}</b></span><span>Saldo<b>{brl(s.balance_cents)}</b></span></div>{txs.slice(0,30).map(t=><div className="report-row" key={t.id}><span>{t.description}<small>{t.due_date||t.created_at.slice(0,10)}</small></span><b>{t.type==='INCOME'?'+':'-'} {brl(t.amount_cents)}</b></div>)}</section></>}
function SettingsPage({me,onLogout,toast}:{me:Me;onLogout:()=>void;toast:(x:string,t?:'ok'|'error')=>void}){const [guests,setGuests]=useState<any[]>([]),[code,setCode]=useState('');async function load(){if(me.role!=='OWNER')return;try{const r=await api<any>('/api/guests');setGuests(r.items||[])}catch(x:any){toast(x.message,'error')}}useEffect(()=>{load()},[me.id]);async function invite(){try{const r=await api<any>('/api/guests',{method:'POST',body:'{}'});setCode(r.code);toast('Convite criado.');load()}catch(x:any){toast(x.message,'error')}}return <><PageHead title="Perfil" subtitle="Conta, segurança e convidados."/><div className="settings"><section className="surface profile"><div className="avatar big">{me.name[0].toUpperCase()}</div><h3>{me.name}</h3><p>{me.email}</p><small>{me.role==='OWNER'?'Conta principal':'Convidado'}</small><button className="secondary danger" onClick={onLogout}><LogOut size={17}/> Sair</button></section><section className="surface profile"><ShieldCheck/><h3>Segurança</h3><p>Seus dados são isolados por conta e todas as operações passam pela API do CONTROL.</p><small className="safe">● Proteção ativa</small></section>{me.role==='OWNER'&&<section className="surface guests"><div className="section-head"><div><h3>Convidados</h3><p>Até 2 pessoas podem compartilhar esta conta.</p></div><button className="primary" disabled={guests.length>=2} onClick={invite}><Users size={17}/> Criar convite</button></div>{code&&<div className="invite"><small>Código para compartilhar</small><b>{code}</b></div>}{guests.map(g=><div className="guest" key={g.id}><div className="avatar">{g.name?.[0]?.toUpperCase()}</div><span><b>{g.name}</b><small>{g.email}</small></span></div>)}{!guests.length&&<Empty text="Nenhum convidado ativo."/>}</section>}</div></>}

export default function App(){
 const [me,setMe]=useState<Me|null>(null),[loading,setLoading]=useState(true),[page,setPage]=useState('home'),[txs,setTxs]=useState<Tx[]>([]),[goals,setGoals]=useState<GoalT[]>([]),[debts,setDebts]=useState<Debt[]>([]),[s,setS]=useState<Summary>({income_cents:0,expense_cents:0,pending_cents:0,balance_cents:0,reserve_cents:0}),[modal,setModal]=useState<string|null>(null),[editingTx,setEditingTx]=useState<Tx|null>(null),[editingGoal,setEditingGoal]=useState<GoalT|null>(null),[paying,setPaying]=useState<Debt|null>(null),[toasts,setToasts]=useState<ToastData[]>([])
 const toast=(text:string,type:'ok'|'error'='ok')=>{const id=Date.now();setToasts(v=>[...v,{id,type,text}]);setTimeout(()=>setToasts(v=>v.filter(x=>x.id!==id)),3200)}
 async function refresh(){const [a,b,c,d]=await Promise.all([api<Summary>('/api/summary'),api<{items:Tx[]}>('/api/transactions'),api<{items:GoalT[]}>('/api/goals'),api<{items:Debt[]}>('/api/debts')]);setS(a);setTxs(b.items);setGoals(c.items);setDebts(d.items)}
 async function load(){try{const m=await api<Me>('/api/me');setMe(m);await refresh()}catch{authStore.clear();setMe(null)}finally{setLoading(false)}}
 useEffect(()=>{const q=new URLSearchParams(location.search);if(q.get('page'))setPage(q.get('page')!);if(q.get('action')==='new-transaction')setModal('tx');authStore.get()?load():setLoading(false)},[])
 async function saveTx(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api(editingTx?`/api/transactions/${editingTx.id}`:'/api/transactions',{method:editingTx?'PUT':'POST',body:JSON.stringify({type:f.get('type'),description:f.get('description'),amount:Number(f.get('amount')),status:f.get('status'),due_date:f.get('due_date')||null,notes:f.get('notes')})});setModal(null);setEditingTx(null);toast(editingTx?'Lançamento atualizado.':'Lançamento salvo.');await refresh()}catch(x:any){toast(x.message,'error')}}
 async function delTx(id:string){if(!confirm('Excluir este lançamento?'))return;try{await api('/api/transactions/'+id,{method:'DELETE'});toast('Lançamento excluído.');await refresh()}catch(x:any){toast(x.message,'error')}}
 async function saveGoal(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api(editingGoal?`/api/goals/${editingGoal.id}`:'/api/goals',{method:editingGoal?'PUT':'POST',body:JSON.stringify({name:f.get('name'),target:Number(f.get('target')),current:Number(f.get('current')||0),deadline:f.get('deadline')||null})});setModal(null);setEditingGoal(null);toast('Meta salva.');await refresh()}catch(x:any){toast(x.message,'error')}}
 async function reserve(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/reserve',{method:'POST',body:JSON.stringify({kind:f.get('kind'),amount:Number(f.get('amount')),note:f.get('note')})});setModal(null);toast('Reserva atualizada.');await refresh()}catch(x:any){toast(x.message,'error')}}
 async function saveDebt(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/debts',{method:'POST',body:JSON.stringify({name:f.get('name'),total:Number(f.get('total')),remaining:Number(f.get('remaining')),due_date:f.get('due_date')||null})});setModal(null);toast('Dívida adicionada.');await refresh()}catch(x:any){toast(x.message,'error')}}
 async function payDebt(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!paying)return;const f=new FormData(e.currentTarget);try{await api(`/api/debts/${paying.id}/payment`,{method:'POST',body:JSON.stringify({amount:Number(f.get('amount')),note:f.get('note')})});setModal(null);setPaying(null);toast('Pagamento registrado.');await refresh()}catch(x:any){toast(x.message,'error')}}
 if(loading)return <div className="loading"><div><Skeleton className="h-28"/><Skeleton className="mt-3 h-64"/></div></div>
 if(!me)return <Auth onReady={m=>{setMe(m);load()}}/>
 const content:Record<string,ReactNode>={home:<Dashboard me={me} s={s} txs={txs} setPage={setPage} onNew={()=>{setEditingTx(null);setModal('tx')}}/>,transactions:<Transactions items={txs} onNew={()=>{setEditingTx(null);setModal('tx')}} onEdit={t=>{setEditingTx(t);setModal('tx')}} onDelete={delTx}/>,goals:<Goals items={goals} onNew={()=>{setEditingGoal(null);setModal('goal')}} onEdit={g=>{setEditingGoal(g);setModal('goal')}}/>,reserve:<Reserve s={s} onMove={()=>setModal('reserve')}/>,debts:<Debts items={debts} onNew={()=>setModal('debt')} onPay={d=>{setPaying(d);setModal('pay')}}/>,calendar:<CalendarPage txs={txs}/>,reports:<Reports s={s} txs={txs}/>,settings:<SettingsPage me={me} onLogout={()=>{authStore.clear();setMe(null)}} toast={toast}/>}
 return <div className="app"><aside className="sidebar no-print"><Brand/><nav>{nav.map(([k,l,I])=><button key={k} className={page===k?'active':''} onClick={()=>setPage(k)}><I size={18}/>{l}</button>)}</nav><div className="sidebar-user"><div className="avatar">{me.name[0].toUpperCase()}</div><span><b>{me.name}</b><small>{me.role==='OWNER'?'Conta principal':'Convidado'}</small></span></div></aside><main><header className="topbar no-print"><div className="mobile-logo"><Brand compact/></div><div className="top-actions"><button className="icon" aria-label="Buscar" onClick={()=>setPage('transactions')}><Search size={19}/></button><button className="icon notify" aria-label="Agenda" onClick={()=>setPage('calendar')}><Bell size={19}/>{s.pending_cents>0&&<i/>}</button><button className="avatar" aria-label="Perfil" onClick={()=>setPage('settings')}>{me.name[0].toUpperCase()}</button></div></header><div className="content"><AnimatePresence mode="wait"><motion.div key={page} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-3}}>{content[page]||content.home}</motion.div></AnimatePresence></div></main><button className="fab no-print" aria-label="Novo lançamento" onClick={()=>{setEditingTx(null);setModal('tx')}}><Plus/></button><nav className="bottom no-print">{[['home','Início',Home],['transactions','Extrato',ReceiptText],['goals','Metas',Target],['reports','Análise',BarChart3],['settings','Perfil',UserRound]].map(([k,l,I]:any)=><button key={k} className={page===k?'active':''} onClick={()=>setPage(k)}><I size={19}/><span>{l}</span></button>)}</nav>
 <Modal open={modal==='tx'} title={editingTx?'Editar lançamento':'Novo lançamento'} onClose={()=>{setModal(null);setEditingTx(null)}}><form className="form" onSubmit={saveTx}><label>Tipo<select className="field" name="type" defaultValue={editingTx?.type||'EXPENSE'}><option value="EXPENSE">Saída</option><option value="INCOME">Entrada</option></select></label><label>Descrição<input className="field" name="description" defaultValue={editingTx?.description||''} required/></label><label>Valor<input className="field" type="number" name="amount" min="0" step="0.01" defaultValue={editingTx?editingTx.amount_cents/100:''} required/></label><label>Status<select className="field" name="status" defaultValue={editingTx?.status||'PAID'}><option value="PAID">Pago</option><option value="PENDING">Pendente</option><option value="OVERDUE">Vencido</option></select></label><label>Data / vencimento<input className="field" type="date" name="due_date" defaultValue={editingTx?.due_date||''}/></label><label>Observações<textarea className="field" name="notes" rows={3}/></label><button className="primary">{editingTx?'Atualizar':'Salvar lançamento'}</button></form></Modal>
 <Modal open={modal==='goal'} title={editingGoal?'Editar meta':'Nova meta'} onClose={()=>{setModal(null);setEditingGoal(null)}}><form className="form" onSubmit={saveGoal}><label>Nome<input className="field" name="name" defaultValue={editingGoal?.name||''} required/></label><label>Valor da meta<input className="field" type="number" step="0.01" name="target" defaultValue={editingGoal?editingGoal.target_cents/100:''} required/></label><label>Valor já guardado<input className="field" type="number" step="0.01" name="current" defaultValue={editingGoal?editingGoal.current_cents/100:''}/></label><label>Prazo<input className="field" type="date" name="deadline" defaultValue={editingGoal?.deadline||''}/></label><button className="primary">Salvar meta</button></form></Modal>
 <Modal open={modal==='reserve'} title="Movimentar reserva" onClose={()=>setModal(null)}><form className="form" onSubmit={reserve}><label>Movimento<select className="field" name="kind"><option value="DEPOSIT">Adicionar</option><option value="WITHDRAW">Retirar</option></select></label><label>Valor<input className="field" type="number" step="0.01" min="0.01" name="amount" required/></label><label>Observação<input className="field" name="note"/></label><button className="primary">Confirmar</button></form></Modal>
 <Modal open={modal==='debt'} title="Nova dívida" onClose={()=>setModal(null)}><form className="form" onSubmit={saveDebt}><label>Descrição<input className="field" name="name" required/></label><label>Valor total<input className="field" type="number" step="0.01" name="total" required/></label><label>Saldo devedor<input className="field" type="number" step="0.01" name="remaining" required/></label><label>Vencimento<input className="field" type="date" name="due_date"/></label><button className="primary">Salvar dívida</button></form></Modal>
 <Modal open={modal==='pay'} title="Abater dívida" onClose={()=>{setModal(null);setPaying(null)}}><form className="form" onSubmit={payDebt}><div className="debt-info"><b>{paying?.name}</b><small>Saldo atual: {brl(paying?.remaining_cents||0)}</small></div><label>Valor pago / haver<input className="field" type="number" step="0.01" min="0.01" max={(paying?.remaining_cents||0)/100} name="amount" required/></label><label>Observação<input className="field" name="note"/></label><button className="primary">Confirmar abatimento</button></form></Modal><Toasts items={toasts} onClose={id=>setToasts(v=>v.filter(x=>x.id!==id))}/></div>
}
