name = "ritmo-api"
main = "src/index.ts"
compatibility_date = "2026-09-07"
workers_dev = true

[observability]
enabled = false

[[d1_databases]]
binding = "DB"
database_name = "ritmo-db"
database_id = "7880a822-de54-48e0-b610-e0e8092656f2"

[[kv_namespaces]]
binding = "AVATARS"
id = "589ab5cb22a4432f902bbdebd1bbd58d"
