const SESSION_COOKIE='ritmo_session';
const enc=new TextEncoder();
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const fail=(message,status=400)=>json({error:message},status);
const uid=(prefix='')=>prefix+crypto.randomUUID();
const cleanEmail=v=>String(v||'').trim().toLowerCase();
const cleanText=(v,max=160)=>String(v||'').trim().slice(0,max);
const num=v=>Number(v||0);
const isoDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||''))?String(v):null;
const nowIso=()=>new Date().toISOString();
const b64u=bytes=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const rand=(n=32)=>crypto.getRandomValues(new Uint8Array(n));
async function sha256(value){const bytes=typeof value==='string'?enc.encode(value):value;return b64u(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)))}
async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations:90000},key,256);return b64u(new Uint8Array(bits))}
async function verifyPassword(password,salt,expected){return (await passwordHash(password,salt))===expected}
function cookie(req,name){const raw=req.headers.get('cookie')||'';for(const p of raw.split(';')){const [k,...v]=p.trim().split('=');if(k===name)return decodeURIComponent(v.join('='))}return null}
function sessionCookie(token,maxAge=60*60*24*30){return `${SESSION_COOKIE}=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
function clearCookie(){return `${SESSION_COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`}
function sameOrigin(req){const origin=req.headers.get('origin');if(!origin)return true;return origin===new URL(req.url).origin}
async function body(req){try{return await req.json()}catch{return {}}}
async function auth(req,env){const token=cookie(req,SESSION_COOKIE);if(!token)return null;const h=await sha256(token);return env.DB.prepare(`SELECT u.id,u.name,u.email,u.avatar_kv_key FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>CURRENT_TIMESTAMP LIMIT 1`).bind(h).first()}
async function createSession(env,userId){const token=b64u(rand(32)),hash=await sha256(token),id=uid('ses_');await env.DB.prepare(`INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,datetime('now','+30 days'))`).bind(id,userId,hash).run();return token}
async function requireUser(req,env){const u=await auth(req,env);if(!u)throw Object.assign(new Error('Sua sessão expirou. Entre novamente.'),{status:401});return u}
function scopeOf(req){const u=new URL(req.url);return req.headers.get('x-ritmo-scope')==='couple'||u.searchParams.get('scope')==='couple'?'couple':'personal'}
async function workspaceFor(env,userId,scope){const type=scope==='couple'?'COUPLE':'PERSONAL';return env.DB.prepare(`SELECT w.id,w.name,w.type FROM workspaces w JOIN workspace_members m ON m.workspace_id=w.id WHERE m.user_id=? AND m.status='ACTIVE' AND w.type=? ORDER BY w.created_at DESC LIMIT 1`).bind(userId,type).first()}
async function memberOf(env,userId,workspaceId){return !!(await env.DB.prepare(`SELECT 1 ok FROM workspace_members WHERE user_id=? AND workspace_id=? AND status='ACTIVE'`).bind(userId,workspaceId).first())}
async function activeCouple(env,userId){const w=await workspaceFor(env,userId,'couple');if(!w)return null;const count=await env.DB.prepare(`SELECT COUNT(*) c FROM workspace_members WHERE workspace_id=? AND status='ACTIVE'`).bind(w.id).first();return Number(count?.c||0)>=2?w:null}
async function defaultSource(env,workspaceId){return env.DB.prepare(`SELECT id FROM money_sources WHERE workspace_id=? AND is_archived=0 ORDER BY created_at LIMIT 1`).bind(workspaceId).first()}
async function defaultCategory(env,workspaceId,type,name){let c=await env.DB.prepare(`SELECT id FROM categories WHERE workspace_id=? AND type=? AND name=? LIMIT 1`).bind(workspaceId,type,name).first();if(c)return c;const id=uid('cat_');await env.DB.prepare(`INSERT INTO categories(id,workspace_id,created_by_user_id,name,type,icon,color,is_default) SELECT ?,?,created_by_user_id,?,?,?, ?,1 FROM workspaces WHERE id=?`).bind(id,workspaceId,name,type,type==='INCOME'?'arrow_upward':'receipt_long',type==='INCOME'?'#15956D':'#D95B62',workspaceId).run();return {id}}
async function idempotent(req,env,user,fn){const key=req.headers.get('idempotency-key');if(!key)return fn();const prev=await env.DB.prepare(`SELECT status_code,response_json FROM idempotency_keys WHERE user_id=? AND idempotency_key=? AND expires_at>CURRENT_TIMESTAMP`).bind(user.id,key).first();if(prev)return new Response(prev.response_json,{status:Number(prev.status_code),headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});const res=await fn();if(res.headers.get('content-type')?.includes('application/json')){const text=await res.clone().text();await env.DB.prepare(`INSERT OR REPLACE INTO idempotency_keys(user_id,idempotency_key,status_code,response_json,expires_at) VALUES(?,?,?,?,datetime('now','+2 days'))`).bind(user.id,key,res.status,text).run()}return res}
async function ensureWorkspaceSeed(env,workspaceId,userId){const s=await defaultSource(env,workspaceId);if(!s){await env.DB.prepare(`INSERT INTO money_sources(id,workspace_id,created_by_user_id,name,type,initial_balance,current_balance,icon,color) VALUES(?,?,?,?,?,?,?,?,?)`).bind(uid('src_'),workspaceId,userId,'Saldo geral','OTHER',0,0,'account_balance_wallet','#0F4C5C').run()}
 const count=await env.DB.prepare(`SELECT COUNT(*) c FROM categories WHERE workspace_id=?`).bind(workspaceId).first();if(Number(count?.c||0)>0)return;
 const cats=[['Salário','INCOME','payments','#15956D'],['Renda extra','INCOME','add_circle','#7CA982'],['Reembolso','INCOME','undo','#D4A373'],['Outros','INCOME','more_horiz','#0F4C5C'],['Alimentação','EXPENSE','restaurant','#D4A373'],['Supermercado','EXPENSE','shopping_cart','#C98855'],['Transporte','EXPENSE','directions_car','#5F8E9A'],['Moradia','EXPENSE','home','#A37F5E'],['Saúde','EXPENSE','favorite','#D95B62'],['Educação','EXPENSE','school','#6B82B5'],['Lazer','EXPENSE','celebration','#A276A8'],['Assinaturas','EXPENSE','subscriptions','#77878B'],['Dívidas','EXPENSE','receipt_long','#B76A5B'],['Outros','EXPENSE','more_horiz','#7CA982']];
 await env.DB.batch(cats.map(([name,type,icon,color])=>env.DB.prepare(`INSERT INTO categories(id,workspace_id,created_by_user_id,name,type,icon,color,is_default) VALUES(?,?,?,?,?,?,?,1)`).bind(uid('cat_'),workspaceId,userId,name,type,icon,color)))}
async function sharingState(env,user){
 const c=await workspaceFor(env,user.id,'couple');let active=false,partner=null;if(c){const members=await env.DB.prepare(`SELECT u.id,u.name,u.email,m.role FROM workspace_members m JOIN users u ON u.id=m.user_id WHERE m.workspace_id=? AND m.status='ACTIVE' ORDER BY m.joined_at`).bind(c.id).all();active=members.results.length>=2;partner=members.results.find(x=>x.id!==user.id)||null}
 const incoming=await env.DB.prepare(`SELECT i.id,i.invited_email,i.expires_at,i.status,u.name inviter_name FROM workspace_invites i JOIN users u ON u.id=i.invited_by_user_id WHERE lower(i.invited_email)=lower(?) AND i.status='PENDING' AND i.expires_at>CURRENT_TIMESTAMP ORDER BY i.created_at DESC`).bind(user.email).all();
 const outgoing=await env.DB.prepare(`SELECT i.id,i.invited_email,i.expires_at,i.status FROM workspace_invites i WHERE i.invited_by_user_id=? AND i.status='PENDING' AND i.expires_at>CURRENT_TIMESTAMP ORDER BY i.created_at DESC`).bind(user.id).all();
 return {active,workspace_id:c?.id||null,partner,incoming:incoming.results,outgoing:outgoing.results.map(x=>({...x,code:x.id}))}
}
async function bootstrap(req,env,user){
 const scope=scopeOf(req),sharing=await sharingState(env,user);if(scope==='couple'&&!sharing.active)throw Object.assign(new Error('Conecte seu parceiro para abrir o Nosso Ritmo.'),{status:409});const ws=await workspaceFor(env,user.id,scope);if(!ws)throw Object.assign(new Error('Perfil financeiro não encontrado.'),{status:404});
 const now=new Date(),year=now.getUTCFullYear(),month=now.getUTCMonth()+1,from=`${year}-${String(month).padStart(2,'0')}-01`,nextMonth=month===12?`${year+1}-01-01`:`${year}-${String(month+1).padStart(2,'0')}-01`;const prevEnd=from,prevDate=new Date(Date.UTC(year,month-2,1)),prevFrom=prevDate.toISOString().slice(0,10);
 const [settings,sources,categories,transactions,goals,debts,budget,summary,prev,contribs]=await Promise.all([
  env.DB.prepare(`SELECT theme,notifications_enabled FROM user_settings WHERE user_id=?`).bind(user.id).first(),
  env.DB.prepare(`SELECT id,name,type,initial_balance,current_balance,color,icon FROM money_sources WHERE workspace_id=? AND is_archived=0 ORDER BY created_at`).bind(ws.id).all(),
  env.DB.prepare(`SELECT id,name,type,icon,color FROM categories WHERE workspace_id=? AND is_archived=0 ORDER BY is_default DESC,name`).bind(ws.id).all(),
  env.DB.prepare(`SELECT t.id,t.type,t.status,t.amount,t.description,t.date,t.due_date,t.paid_at,t.notes,c.name category_name,c.color category_color,u.name created_by_name,s.name money_source_name FROM transactions t LEFT JOIN categories c ON c.id=t.category_id LEFT JOIN users u ON u.id=t.created_by_user_id LEFT JOIN money_sources s ON s.id=t.money_source_id WHERE t.workspace_id=? AND t.deleted_at IS NULL ORDER BY t.date DESC,t.created_at DESC LIMIT 250`).bind(ws.id).all(),
  env.DB.prepare(`SELECT id,title,target_amount,current_amount,deadline,icon,color,kind,status FROM goals WHERE workspace_id=? AND status!='ARCHIVED' ORDER BY status,created_at DESC`).bind(ws.id).all(),
  env.DB.prepare(`SELECT id,title,total_amount,remaining_amount,status,due_date,notes FROM debts WHERE workspace_id=? AND status!='CANCELED' ORDER BY status,due_date IS NULL,due_date`).bind(ws.id).all(),
  env.DB.prepare(`SELECT id,year,month,total_amount FROM budgets WHERE workspace_id=? AND year=? AND month=?`).bind(ws.id,year,month).first(),
  env.DB.prepare(`SELECT COALESCE(SUM(CASE WHEN type='INCOME' AND status='PAID' THEN amount ELSE 0 END),0) all_income,COALESCE(SUM(CASE WHEN type='EXPENSE' AND status='PAID' THEN amount ELSE 0 END),0) all_expenses,COALESCE(SUM(CASE WHEN type='INCOME' AND status='PAID' AND date>=? AND date<? THEN amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN type='EXPENSE' AND status='PAID' AND date>=? AND date<? THEN amount ELSE 0 END),0) expenses,COALESCE(SUM(CASE WHEN type='EXPENSE' AND status='PENDING' THEN amount ELSE 0 END),0) pending,COALESCE(SUM(CASE WHEN type='EXPENSE' AND status='PENDING' AND due_date<CURRENT_DATE THEN 1 ELSE 0 END),0) overdue FROM transactions WHERE workspace_id=? AND deleted_at IS NULL`).bind(from,nextMonth,from,nextMonth,ws.id).first(),
  env.DB.prepare(`SELECT COALESCE(SUM(CASE WHEN type='INCOME' AND status='PAID' THEN amount WHEN type='EXPENSE' AND status='PAID' THEN -amount ELSE 0 END),0) net FROM transactions WHERE workspace_id=? AND deleted_at IS NULL AND date>=? AND date<?`).bind(ws.id,prevFrom,prevEnd).first(),
  sharing.active?env.DB.prepare(`SELECT cc.id,cc.amount,cc.date,cc.description,u.name created_by_name FROM couple_contributions cc JOIN users u ON u.id=cc.created_by_user_id WHERE cc.workspace_id=? ORDER BY cc.date DESC,cc.created_at DESC LIMIT 100`).bind(sharing.workspace_id).all():Promise.resolve({results:[]})
 ]);
 let budgetObj=null;if(budget){const rows=await env.DB.prepare(`SELECT bc.id,bc.category_id,c.name category_name,bc.limit_amount,c.color,COALESCE(SUM(CASE WHEN t.type='EXPENSE' AND t.status='PAID' AND t.deleted_at IS NULL AND t.date>=? AND t.date<? THEN t.amount ELSE 0 END),0) spent FROM budget_categories bc JOIN categories c ON c.id=bc.category_id LEFT JOIN transactions t ON t.category_id=bc.category_id AND t.workspace_id=? WHERE bc.budget_id=? GROUP BY bc.id,bc.category_id,c.name,bc.limit_amount,c.color ORDER BY c.name`).bind(from,nextMonth,ws.id,budget.id).all();budgetObj={...budget,categories:rows.results}}
 const net=Number(summary.income)-Number(summary.expenses),prevNet=Number(prev?.net||0),monthChange=prevNet===0?0:Math.round(((net-prevNet)/Math.abs(prevNet))*100);return {scope,workspace:ws,profile:{id:user.id,name:user.name,email:user.email,avatar_url:user.avatar_kv_key?`/api/avatar/${user.id}`:null},partner:sharing.partner,sharing,sources:sources.results,categories:categories.results,transactions:transactions.results,goals:goals.results,debts:debts.results,budget:budgetObj,contributions:contribs.results,summary:{balance:Number(summary.all_income)-Number(summary.all_expenses),income:Number(summary.income),expenses:Number(summary.expenses),pending:Number(summary.pending),overdue:Number(summary.overdue),monthChange},settings:{theme:settings?.theme||'SYSTEM',notifications_enabled:Number(settings?.notifications_enabled??1)},server_time:nowIso()}
}
function secureAssets(res){const h=new Headers(res.headers);h.set('x-frame-options','DENY');h.set('x-content-type-options','nosniff');h.set('referrer-policy','strict-origin-when-cross-origin');h.set('permissions-policy','camera=(self), microphone=(), geolocation=()');h.set('content-security-policy',"default-src 'self'; img-src 'self' blob: data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; font-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");return new Response(res.body,{status:res.status,statusText:res.statusText,headers:h})}
async function route(req,env){
 const url=new URL(req.url),p=url.pathname,m=req.method;if(p==='/api/health')return json({ok:true,service:'ritmo',version:'2.0.0',product:'gestao-financeira-pessoal'});
 if(p.startsWith('/api/')&&m!=='GET'&&!sameOrigin(req))return fail('Origem não permitida.',403);
 if(p==='/api/auth/register'&&m==='POST'){const b=await body(req),name=cleanText(b.name,80),email=cleanEmail(b.email),password=String(b.password||'');if(name.length<2||!email.includes('@')||password.length<8)return fail('Informe nome, e-mail e uma senha com pelo menos 8 caracteres.');if(await env.DB.prepare(`SELECT 1 x FROM users WHERE email=?`).bind(email).first())return fail('Já existe uma conta com este e-mail.',409);const id=uid('usr_'),salt=b64u(rand(16)),hash=await passwordHash(password,salt),ws=uid('wsp_');const statements=[env.DB.prepare(`INSERT INTO users(id,name,email,password_hash,password_salt) VALUES(?,?,?,?,?)`).bind(id,name,email,hash,salt),env.DB.prepare(`INSERT INTO user_settings(user_id) VALUES(?)`).bind(id),env.DB.prepare(`INSERT INTO workspaces(id,type,name,created_by_user_id) VALUES(?,?,?,?)`).bind(ws,'PERSONAL','Ritmo',id),env.DB.prepare(`INSERT INTO workspace_members(workspace_id,user_id,role) VALUES(?,?,?)`).bind(ws,id,'OWNER')];await env.DB.batch(statements);await ensureWorkspaceSeed(env,ws,id);const token=await createSession(env,id);return json({ok:true},201,{'set-cookie':sessionCookie(token)})}
 if(p==='/api/auth/login'&&m==='POST'){const b=await body(req),email=cleanEmail(b.email),password=String(b.password||''),u=await env.DB.prepare(`SELECT id,name,email,password_hash,password_salt FROM users WHERE email=?`).bind(email).first();if(!u||!(await verifyPassword(password,u.password_salt,u.password_hash)))return fail('E-mail ou senha incorretos.',401);await env.DB.prepare(`DELETE FROM sessions WHERE user_id=? AND (expires_at<=CURRENT_TIMESTAMP OR revoked_at IS NOT NULL)`).bind(u.id).run();const token=await createSession(env,u.id);return json({ok:true},200,{'set-cookie':sessionCookie(token)})}
 if(p==='/api/auth/logout'&&m==='POST'){const token=cookie(req,SESSION_COOKIE);if(token){const h=await sha256(token);await env.DB.prepare(`UPDATE sessions SET revoked_at=CURRENT_TIMESTAMP WHERE token_hash=?`).bind(h).run()}return json({ok:true},200,{'set-cookie':clearCookie()})}
 if(p.startsWith('/api/avatar/')&&m==='GET'){const user=await requireUser(req,env),target=p.split('/').pop();if(target!==user.id){const c=await activeCouple(env,user.id);if(!c||!(await memberOf(env,target,c.id)))return fail('Não autorizado.',403)}const row=await env.DB.prepare(`SELECT avatar_kv_key FROM users WHERE id=?`).bind(target).first();if(!row?.avatar_kv_key)return new Response(null,{status:404});const val=await env.AVATARS.get(row.avatar_kv_key,{type:'arrayBuffer'});if(!val)return new Response(null,{status:404});return new Response(val,{headers:{'content-type':'image/webp','cache-control':'private, max-age=3600'}})}
 const user=await requireUser(req,env);
 if(p==='/api/bootstrap'&&m==='GET')return json(await bootstrap(req,env,user));
 if(p==='/api/avatar'&&m==='PUT')return idempotent(req,env,user,async()=>{if(req.headers.get('content-type')!=='image/webp')return fail('Envie a foto em WebP.',415);const bytes=await req.arrayBuffer();if(bytes.byteLength>20*1024)return fail('A foto deve ter no máximo 20 KB.');const key=`avatar:${user.id}`;await env.AVATARS.put(key,bytes,{metadata:{contentType:'image/webp'}});await env.DB.prepare(`UPDATE users SET avatar_kv_key=?,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=?`).bind(key,user.id).run();return json({ok:true,url:`/api/avatar/${user.id}`})});
 if(p==='/api/settings'&&m==='PATCH')return idempotent(req,env,user,async()=>{const b=await body(req),theme=['LIGHT','DARK','SYSTEM'].includes(b.theme)?b.theme:null;if(theme)await env.DB.prepare(`UPDATE user_settings SET theme=?,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE user_id=?`).bind(theme,user.id).run();return json({ok:true})});
 const scope=scopeOf(req),ws=await workspaceFor(env,user.id,scope);if(!ws&& !p.startsWith('/api/sharing')&&!p.startsWith('/api/couple/'))return fail('Perfil financeiro não encontrado.',404);
 if(p==='/api/transactions'&&m==='POST')return idempotent(req,env,user,async()=>{const b=await body(req),type=b.type==='INCOME'?'INCOME':'EXPENSE',amount=num(b.amount),description=cleanText(b.description,120),date=isoDate(b.date),due=isoDate(b.due_date),source=cleanText(b.money_source_id,80),category=cleanText(b.category_id,80);let status=b.status==='PENDING'?'PENDING':'PAID';if(type==='EXPENSE'&&date&&date>new Date().toISOString().slice(0,10))status='PENDING';if(amount<=0||!description||!date)return fail('Preencha descrição, valor e data.');if(!(await env.DB.prepare(`SELECT 1 x FROM money_sources WHERE id=? AND workspace_id=?`).bind(source,ws.id).first()))return fail('Fonte inválida.');if(category&&!(await env.DB.prepare(`SELECT 1 x FROM categories WHERE id=? AND workspace_id=? AND type=?`).bind(category,ws.id,type).first()))return fail('Categoria inválida.');await env.DB.prepare(`INSERT INTO transactions(id,workspace_id,created_by_user_id,money_source_id,category_id,type,status,amount,description,date,due_date,paid_at,notes,client_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(uid('tx_'),ws.id,user.id,source,category||null,type,status,amount,description,date,due,status==='PAID'?nowIso():null,cleanText(b.notes,400)||null,req.headers.get('x-ritmo-client')).run();return json({ok:true},201)});
 const txMatch=p.match(/^\/api\/transactions\/([^/]+)$/);if(txMatch&&m==='PATCH')return idempotent(req,env,user,async()=>{const id=txMatch[1],old=await env.DB.prepare(`SELECT * FROM transactions WHERE id=? AND workspace_id=? AND deleted_at IS NULL`).bind(id,ws.id).first();if(!old)return fail('Lançamento não encontrado.',404);const b=await body(req),type=b.type==='INCOME'?'INCOME':'EXPENSE',amount=num(b.amount),description=cleanText(b.description,120),date=isoDate(b.date),due=isoDate(b.due_date),source=cleanText(b.money_source_id,80),category=cleanText(b.category_id,80),status=b.status==='PENDING'?'PENDING':'PAID';if(amount<=0||!description||!date)return fail('Dados inválidos.');await env.DB.prepare(`UPDATE transactions SET money_source_id=?,category_id=?,type=?,status=?,amount=?,description=?,date=?,due_date=?,paid_at=?,notes=?,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=? AND workspace_id=?`).bind(source,category||null,type,status,amount,description,date,due,status==='PAID'?(old.paid_at||nowIso()):null,cleanText(b.notes,400)||null,id,ws.id).run();return json({ok:true})});
 if(txMatch&&m==='DELETE')return idempotent(req,env,user,async()=>{await env.DB.prepare(`UPDATE transactions SET deleted_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=? AND workspace_id=?`).bind(txMatch[1],ws.id).run();return json({ok:true})});
 if(p==='/api/goals'&&m==='POST')return idempotent(req,env,user,async()=>{const b=await body(req),title=cleanText(b.title,100),target=num(b.target_amount),deadline=isoDate(b.deadline),kind=b.kind==='EMERGENCY_RESERVE'?'EMERGENCY_RESERVE':'GOAL';if(!title||target<=0)return fail('Informe nome e valor alvo.');await env.DB.prepare(`INSERT INTO goals(id,workspace_id,created_by_user_id,title,target_amount,current_amount,deadline,kind,icon,color) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(uid('goal_'),ws.id,user.id,title,target,0,deadline,kind,kind==='EMERGENCY_RESERVE'?'shield':'flag',kind==='EMERGENCY_RESERVE'?'#0F4C5C':'#7CA982').run();return json({ok:true},201)});
 const goalMatch=p.match(/^\/api\/goals\/([^/]+)$/);if(goalMatch&&m==='PATCH')return idempotent(req,env,user,async()=>{const b=await body(req),title=cleanText(b.title,100),target=num(b.target_amount),deadline=isoDate(b.deadline),kind=b.kind==='EMERGENCY_RESERVE'?'EMERGENCY_RESERVE':'GOAL';await env.DB.prepare(`UPDATE goals SET title=?,target_amount=?,deadline=?,kind=?,updated_at=CURRENT_TIMESTAMP,version=version+1,status=CASE WHEN current_amount>=? THEN 'COMPLETED' ELSE 'ACTIVE' END WHERE id=? AND workspace_id=?`).bind(title,target,deadline,kind,target,goalMatch[1],ws.id).run();return json({ok:true})});
 if(goalMatch&&m==='DELETE')return idempotent(req,env,user,async()=>{await env.DB.prepare(`DELETE FROM goals WHERE id=? AND workspace_id=?`).bind(goalMatch[1],ws.id).run();return json({ok:true})});
 const goalEntry=p.match(/^\/api\/goals\/([^/]+)\/entries$/);if(goalEntry&&m==='POST')return idempotent(req,env,user,async()=>{const b=await body(req),amount=num(b.amount),date=isoDate(b.entry_date);if(amount<=0||!date)return fail('Informe valor e data.');const g=await env.DB.prepare(`SELECT current_amount,target_amount FROM goals WHERE id=? AND workspace_id=?`).bind(goalEntry[1],ws.id).first();if(!g)return fail('Meta não encontrada.',404);const next=Number(g.current_amount)+amount,status=next>=Number(g.target_amount)?'COMPLETED':'ACTIVE';await env.DB.batch([env.DB.prepare(`INSERT INTO goal_entries(id,goal_id,workspace_id,created_by_user_id,amount,entry_date,note) VALUES(?,?,?,?,?,?,?)`).bind(uid('ge_'),goalEntry[1],ws.id,user.id,amount,date,cleanText(b.note,300)||null),env.DB.prepare(`UPDATE goals SET current_amount=?,status=?,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=?`).bind(next,status,goalEntry[1])]);return json({ok:true})});
 if(p==='/api/debts'&&m==='POST')return idempotent(req,env,user,async()=>{const b=await body(req),title=cleanText(b.title,100),total=num(b.total_amount),due=isoDate(b.due_date);if(!title||total<=0)return fail('Informe dívida e valor total.');await env.DB.prepare(`INSERT INTO debts(id,workspace_id,created_by_user_id,title,total_amount,remaining_amount,due_date,notes) VALUES(?,?,?,?,?,?,?,?)`).bind(uid('debt_'),ws.id,user.id,title,total,total,due,cleanText(b.notes,400)||null).run();return json({ok:true},201)});
 const debtMatch=p.match(/^\/api\/debts\/([^/]+)$/);if(debtMatch&&m==='PATCH')return idempotent(req,env,user,async()=>{const b=await body(req),old=await env.DB.prepare(`SELECT total_amount,remaining_amount FROM debts WHERE id=? AND workspace_id=?`).bind(debtMatch[1],ws.id).first();if(!old)return fail('Dívida não encontrada.',404);const total=num(b.total_amount),paid=Number(old.total_amount)-Number(old.remaining_amount),remaining=Math.max(0,total-paid);await env.DB.prepare(`UPDATE debts SET title=?,total_amount=?,remaining_amount=?,due_date=?,notes=?,status=?,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=? AND workspace_id=?`).bind(cleanText(b.title,100),total,remaining,isoDate(b.due_date),cleanText(b.notes,400)||null,remaining<=0?'PAID':'PENDING',debtMatch[1],ws.id).run();return json({ok:true})});
 if(debtMatch&&m==='DELETE')return idempotent(req,env,user,async()=>{await env.DB.prepare(`DELETE FROM debts WHERE id=? AND workspace_id=?`).bind(debtMatch[1],ws.id).run();return json({ok:true})});
 const payMatch=p.match(/^\/api\/debts\/([^/]+)\/payments$/);if(payMatch&&m==='POST')return idempotent(req,env,user,async()=>{const b=await body(req),amount=num(b.amount),date=isoDate(b.payment_date),source=cleanText(b.money_source_id,80),d=await env.DB.prepare(`SELECT remaining_amount,title FROM debts WHERE id=? AND workspace_id=?`).bind(payMatch[1],ws.id).first();if(!d)return fail('Dívida não encontrada.',404);if(amount<=0||amount>Number(d.remaining_amount)||!date)return fail('Pagamento inválido.');const cat=await defaultCategory(env,ws.id,'EXPENSE','Dívidas'),paymentId=uid('dp_'),remaining=Number(d.remaining_amount)-amount;await env.DB.batch([env.DB.prepare(`INSERT INTO debt_payments(id,debt_id,workspace_id,created_by_user_id,money_source_id,amount,payment_date) VALUES(?,?,?,?,?,?,?)`).bind(paymentId,payMatch[1],ws.id,user.id,source,amount,date),env.DB.prepare(`INSERT INTO transactions(id,workspace_id,created_by_user_id,money_source_id,category_id,debt_payment_id,type,status,amount,description,date,paid_at) VALUES(?,?,?,?,?,?, 'EXPENSE','PAID',?,?,?)`).bind(uid('tx_'),ws.id,user.id,source,cat.id,paymentId,amount,`Pagamento: ${d.title}`,date,nowIso()),env.DB.prepare(`UPDATE debts SET remaining_amount=?,status=?,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=?`).bind(remaining,remaining<=0?'PAID':'PENDING',payMatch[1])]);return json({ok:true})});
 if(p==='/api/budget'&&m==='POST')return idempotent(req,env,user,async()=>{const b=await body(req),year=Number(b.year),month=Number(b.month),total=num(b.total_amount);if(year<2020||month<1||month>12||total<0)return fail('Orçamento inválido.');let bud=await env.DB.prepare(`SELECT id FROM budgets WHERE workspace_id=? AND year=? AND month=?`).bind(ws.id,year,month).first();if(!bud){bud={id:uid('bud_')};await env.DB.prepare(`INSERT INTO budgets(id,workspace_id,created_by_user_id,year,month,total_amount) VALUES(?,?,?,?,?,?)`).bind(bud.id,ws.id,user.id,year,month,total).run()}else await env.DB.prepare(`UPDATE budgets SET total_amount=?,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=?`).bind(total,bud.id).run();await env.DB.prepare(`DELETE FROM budget_categories WHERE budget_id=?`).bind(bud.id).run();const cats=Array.isArray(b.categories)?b.categories:[];if(cats.length)await env.DB.batch(cats.slice(0,50).filter(x=>num(x.limit_amount)>0).map(x=>env.DB.prepare(`INSERT INTO budget_categories(id,budget_id,workspace_id,category_id,limit_amount) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM categories WHERE id=? AND workspace_id=? AND type='EXPENSE')`).bind(uid('bc_'),bud.id,ws.id,x.category_id,num(x.limit_amount),x.category_id,ws.id)));return json({ok:true})});
 if(p==='/api/sharing/invite'&&m==='POST')return idempotent(req,env,user,async()=>{const b=await body(req),email=cleanEmail(b.email);if(email===user.email)return fail('Convide outra pessoa.');const target=await env.DB.prepare(`SELECT id,name,email FROM users WHERE email=?`).bind(email).first();if(!target)return fail('Essa pessoa ainda não tem conta no Ritmo.',404);if(await activeCouple(env,user.id))return fail('Você já possui um Nosso Ritmo ativo.',409);if(await activeCouple(env,target.id))return fail('Essa pessoa já participa de outro Nosso Ritmo.',409);let couple=await workspaceFor(env,user.id,'couple');if(!couple){couple={id:uid('wsp_')};await env.DB.batch([env.DB.prepare(`INSERT INTO workspaces(id,type,name,created_by_user_id) VALUES(?,?,?,?)`).bind(couple.id,'COUPLE','Nosso Ritmo',user.id),env.DB.prepare(`INSERT INTO workspace_members(workspace_id,user_id,role) VALUES(?,?,?)`).bind(couple.id,user.id,'OWNER')]);await ensureWorkspaceSeed(env,couple.id,user.id)}const code=b64u(rand(6)).replace(/[-_]/g,'').slice(0,8).toUpperCase(),hash=await sha256(code);await env.DB.prepare(`INSERT INTO workspace_invites(id,workspace_id,invited_by_user_id,invited_email,token_hash,expires_at) VALUES(?,?,?,?,?,datetime('now','+7 days'))`).bind(code,couple.id,user.id,email,hash).run();return json({ok:true,code},201)});
 if(p==='/api/sharing/accept'&&m==='POST')return idempotent(req,env,user,async()=>{const b=await body(req),code=cleanText(b.code,12).toUpperCase(),hash=await sha256(code),inv=await env.DB.prepare(`SELECT * FROM workspace_invites WHERE id=? AND token_hash=? AND lower(invited_email)=lower(?) AND status='PENDING' AND expires_at>CURRENT_TIMESTAMP`).bind(code,hash,user.email).first();if(!inv)return fail('Código inválido ou expirado.',404);if(await activeCouple(env,user.id))return fail('Você já possui um Nosso Ritmo ativo.',409);const members=await env.DB.prepare(`SELECT COUNT(*) c FROM workspace_members WHERE workspace_id=? AND status='ACTIVE'`).bind(inv.workspace_id).first();if(Number(members?.c||0)>=2)return fail('Este convite já foi utilizado.',409);await env.DB.batch([env.DB.prepare(`INSERT OR REPLACE INTO workspace_members(workspace_id,user_id,role,status,joined_at) VALUES(?,?,?,'ACTIVE',CURRENT_TIMESTAMP)`).bind(inv.workspace_id,user.id,'PARTNER'),env.DB.prepare(`UPDATE workspace_invites SET status='ACCEPTED',accepted_at=CURRENT_TIMESTAMP WHERE id=?`).bind(inv.id)]);await ensureWorkspaceSeed(env,inv.workspace_id,user.id);return json({ok:true})});
 const acceptInv=p.match(/^\/api\/sharing\/invites\/([^/]+)\/accept$/);if(acceptInv&&m==='POST')return idempotent(req,env,user,async()=>{const code=acceptInv[1],hash=await sha256(code),inv=await env.DB.prepare(`SELECT * FROM workspace_invites WHERE id=? AND token_hash=? AND lower(invited_email)=lower(?) AND status='PENDING' AND expires_at>CURRENT_TIMESTAMP`).bind(code,hash,user.email).first();if(!inv)return fail('Convite inválido.',404);await env.DB.batch([env.DB.prepare(`INSERT OR REPLACE INTO workspace_members(workspace_id,user_id,role,status,joined_at) VALUES(?,?,?,'ACTIVE',CURRENT_TIMESTAMP)`).bind(inv.workspace_id,user.id,'PARTNER'),env.DB.prepare(`UPDATE workspace_invites SET status='ACCEPTED',accepted_at=CURRENT_TIMESTAMP WHERE id=?`).bind(inv.id)]);await ensureWorkspaceSeed(env,inv.workspace_id,user.id);return json({ok:true})});
 const inviteDelete=p.match(/^\/api\/sharing\/invites\/([^/]+)$/);if(inviteDelete&&m==='DELETE')return idempotent(req,env,user,async()=>{await env.DB.prepare(`UPDATE workspace_invites SET status='CANCELED' WHERE id=? AND invited_by_user_id=? AND status='PENDING'`).bind(inviteDelete[1],user.id).run();return json({ok:true})});
 if(p==='/api/couple/contributions'&&m==='POST')return idempotent(req,env,user,async()=>{const couple=await activeCouple(env,user.id);if(!couple)return fail('Conecte seu parceiro primeiro.',409);const b=await body(req),amount=num(b.amount),date=isoDate(b.date),description=cleanText(b.description,120)||'Contribuição';if(amount<=0||!date)return fail('Informe valor e data.');const source=await defaultSource(env,couple.id),cat=await defaultCategory(env,couple.id,'INCOME','Contribuição'),cid=uid('cc_');await env.DB.batch([env.DB.prepare(`INSERT INTO couple_contributions(id,workspace_id,created_by_user_id,amount,date,description) VALUES(?,?,?,?,?,?)`).bind(cid,couple.id,user.id,amount,date,description),env.DB.prepare(`INSERT INTO transactions(id,workspace_id,created_by_user_id,money_source_id,category_id,type,status,amount,description,date,paid_at,notes) VALUES(?,?,?,?,?,'INCOME','PAID',?,?,?,?)`).bind(uid('tx_'),couple.id,user.id,source.id,cat.id,amount,description,date,nowIso(),'Registro do Nosso Ritmo; não movimenta dinheiro real.')]);return json({ok:true})});
 return fail('Rota não encontrada.',404)
}
export default{async fetch(req,env){try{const u=new URL(req.url);if(u.pathname.startsWith('/api/'))return await route(req,env);if(env.ASSETS)return secureAssets(await env.ASSETS.fetch(req));return new Response('Ritmo',{status:200})}catch(err){console.error(err);return fail(err?.message||'Erro interno.',Number(err?.status||500))}}}
