import {hashPassword,id,json,session,signSession,verifyPassword} from '../_lib/auth'
type Env={DB:any;FILES?:any;JWT_SECRET?:string;SESSION_SECRET?:string;VAPID_PUBLIC_KEY?:string;NOTIFICATION_WORKER_URL?:string}
type Ctx={request:Request;env:Env;params:Record<string,unknown>}
const money=(v:any)=>Math.round(Number(v||0)*100)
const parse=async(r:Request)=>{try{return await r.json() as any}catch{return {}}}
const route=(p:Record<string,unknown>)=>'/'+(Array.isArray(p.path)?p.path.join('/'):String(p.path||''))
const today=()=>new Date().toISOString().slice(0,10)
async function audit(env:Env,tenant:string,uid:string,action:string,entity?:string,eid?:string,details?:any){await env.DB.prepare('INSERT INTO audit_logs(id,tenant_id,user_id,action,entity,entity_id,details) VALUES(?,?,?,?,?,?,?)').bind(id('audit'),tenant,uid,action,entity||null,eid||null,details?JSON.stringify(details).slice(0,4000):null).run()}
async function auth(request:Request,env:Env){return session(request,env)}
async function requireAuth(request:Request,env:Env){const s:any=await auth(request,env);if(!s)throw Object.assign(new Error('Sessão expirada.'),{status:401});return s}
async function scheduleJob(env:Env,userId:string,kind:string,title:string,body:string,sendAt:number,dueAt?:string){await env.DB.prepare("INSERT INTO notification_jobs(id,user_id,kind,title,body,url,send_at,due_at,status) VALUES(?,?,?,?,?,'/',?,?, 'pending')").bind(id('job'),userId,kind,title,body,sendAt,dueAt||null).run()}
async function rebuildJobs(env:Env,userId:string){await env.DB.prepare("DELETE FROM notification_jobs WHERE user_id=? AND status='pending'").bind(userId).run();const {results}=await env.DB.prepare("SELECT type,description,amount_cents,status,due_date FROM transactions WHERE user_id=? AND due_date IS NOT NULL AND status!='PAID' ORDER BY due_date LIMIT 200").bind(userId).all();for(const t of results||[]){const d=String(t.due_date),ts=new Date(d+'T09:00:00-03:00').getTime();if(!Number.isFinite(ts))continue;const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(t.amount_cents)/100);const verb=t.type==='INCOME'?'entrada':'despesa';await scheduleJob(env,userId,t.type==='INCOME'?'income_due':'expense_due',`${t.description} — ${brl}`,`Sua ${verb} de ${brl} está prevista para ${d===today()?'hoje':'amanhã'}.`,ts,d)}}
export const onRequest=async({request,env,params}:Ctx)=>{try{const path=route(params),method=request.method.toUpperCase(),url=new URL(request.url)
 if(path==='/health'&&method==='GET')return json({ok:true,service:'CONTROL',version:'4.0.0'})
 if(path==='/auth/register'&&method==='POST'){const b=await parse(request);if(!b.name||!b.email||String(b.password||'').length<6)return json({error:'Preencha nome, e-mail e uma senha com 6+ caracteres.'},400);const email=String(b.email).trim().toLowerCase();if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return json({error:'Este e-mail já está cadastrado.'},409);const tenant=id('acc'),uid=id('usr'),hash=await hashPassword(String(b.password));await env.DB.batch([env.DB.prepare('INSERT INTO tenants(id,name) VALUES(?,?)').bind(tenant,String(b.tenantName||`Conta de ${b.name}`).trim()),env.DB.prepare("INSERT INTO users(id,tenant_id,name,email,password_hash,role) VALUES(?,?,?,?,?,'OWNER')").bind(uid,tenant,String(b.name).trim(),email,hash)]);const user={id:uid,tenant_id:tenant,name:String(b.name).trim(),email,role:'OWNER'};return json({token:await signSession(env,{uid,tenant,role:'OWNER'}),user},201)}
 if(path==='/auth/login'&&method==='POST'){const b=await parse(request),email=String(b.email||'').trim().toLowerCase(),u:any=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(!u||!await verifyPassword(String(b.password||''),u.password_hash))return json({error:'E-mail ou senha inválidos.'},401);const user={id:u.id,tenant_id:u.tenant_id,name:u.name,email:u.email,role:u.role};return json({token:await signSession(env,{uid:u.id,tenant:u.tenant_id,role:u.role}),user})}
 if(path==='/auth/invite'&&method==='POST'){const b=await parse(request);if(!b.code||!b.name||!b.email||String(b.password||'').length<6)return json({error:'Informe código, nome, e-mail e senha.'},400);const code=String(b.code).trim().toUpperCase(),email=String(b.email).trim().toLowerCase(),inv:any=await env.DB.prepare("SELECT * FROM invites WHERE code=? AND status='PENDING'").bind(code).first();if(!inv)return json({error:'Convite inválido ou já utilizado.'},404);if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return json({error:'E-mail já cadastrado.'},409);const c:any=await env.DB.prepare("SELECT COUNT(*) n FROM users WHERE tenant_id=? AND role='GUEST'").bind(inv.tenant_id).first();if(Number(c.n)>=2)return json({error:'Esta conta já possui 2 convidados.'},409);const uid=id('usr'),hash=await hashPassword(String(b.password));await env.DB.batch([env.DB.prepare("INSERT INTO users(id,tenant_id,name,email,password_hash,role) VALUES(?,?,?,?,?,'GUEST')").bind(uid,inv.tenant_id,String(b.name).trim(),email,hash),env.DB.prepare("UPDATE invites SET status='ACCEPTED' WHERE id=?").bind(inv.id)]);const user={id:uid,tenant_id:inv.tenant_id,name:String(b.name).trim(),email,role:'GUEST'};return json({token:await signSession(env,{uid,tenant:inv.tenant_id,role:'GUEST'}),user},201)}
 const s:any=await requireAuth(request,env),tenant=s.tenant,uid=s.uid
 if(path==='/me'&&method==='GET'){const u=await env.DB.prepare('SELECT id,tenant_id,name,email,role FROM users WHERE id=? AND tenant_id=?').bind(uid,tenant).first();return u?json(u):json({error:'Usuário não encontrado.'},404)}
 if(path==='/summary'&&method==='GET'){const r:any=await env.DB.prepare("SELECT COALESCE(SUM(CASE WHEN type='INCOME' AND status='PAID' THEN amount_cents ELSE 0 END),0) income_cents,COALESCE(SUM(CASE WHEN type='EXPENSE' AND status='PAID' THEN amount_cents ELSE 0 END),0) expense_cents,COALESCE(SUM(CASE WHEN type='INCOME' AND status IN('PENDING','OVERDUE') THEN amount_cents ELSE 0 END),0) receivable_cents,COALESCE(SUM(CASE WHEN type='EXPENSE' AND status IN('PENDING','OVERDUE') THEN amount_cents ELSE 0 END),0) payable_cents FROM transactions WHERE tenant_id=?").bind(tenant).first();const rr:any=await env.DB.prepare("SELECT COALESCE(SUM(CASE WHEN kind='DEPOSIT' THEN amount_cents ELSE -amount_cents END),0) reserve_cents FROM reserve_entries WHERE tenant_id=?").bind(tenant).first();const base:any=await env.DB.prepare('SELECT base_balance_cents FROM account_settings WHERE tenant_id=?').bind(tenant).first();const income=Number(r.income_cents||0),expense=Number(r.expense_cents||0),balance=Number(base?.base_balance_cents||0)+income-expense;return json({...r,balance_cents:balance,pending_cents:Number(r.receivable_cents||0)+Number(r.payable_cents||0),projected_balance_cents:balance+Number(r.receivable_cents||0)-Number(r.payable_cents||0),reserve_cents:Number(rr?.reserve_cents||0)})}
 if(path==='/transactions'&&method==='GET'){const {results}=await env.DB.prepare('SELECT t.*,c.name category FROM transactions t LEFT JOIN categories c ON c.id=t.category_id WHERE t.tenant_id=? ORDER BY COALESCE(t.due_date,t.created_at) DESC,t.created_at DESC LIMIT 500').bind(tenant).all();return json({items:results})}
 if(path==='/transactions'&&method==='POST'){const b=await parse(request);if(!['INCOME','EXPENSE'].includes(b.type)||!String(b.description||'').trim()||!Number.isFinite(Number(b.amount))||Number(b.amount)<0)return json({error:'Dados do lançamento inválidos.'},400);const rid=id('tx'),status=['PENDING','OVERDUE'].includes(String(b.status))?String(b.status):'PAID';await env.DB.prepare('INSERT INTO transactions(id,tenant_id,user_id,type,description,amount_cents,category_id,status,due_date,paid_at,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(rid,tenant,uid,b.type,String(b.description).trim(),money(b.amount),b.category_id||null,status,b.due_date||null,status==='PAID'?new Date().toISOString():null,b.notes||null).run();await audit(env,tenant,uid,'CREATE','transaction',rid);if(status!=='PAID'&&b.due_date)await rebuildJobs(env,uid);return json({id:rid},201)}
 let m=path.match(/^\/transactions\/([^/]+)$/);if(m&&method==='PUT'){const b=await parse(request),cur:any=await env.DB.prepare('SELECT * FROM transactions WHERE id=? AND tenant_id=?').bind(m[1],tenant).first();if(!cur)return json({error:'Lançamento não encontrado.'},404);const status=['PENDING','OVERDUE','PAID'].includes(String(b.status))?String(b.status):cur.status;await env.DB.prepare('UPDATE transactions SET type=?,description=?,amount_cents=?,status=?,due_date=?,paid_at=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=?').bind(b.type||cur.type,String(b.description||cur.description).trim(),b.amount===undefined?cur.amount_cents:money(b.amount),status,b.due_date??cur.due_date,status==='PAID'?(cur.paid_at||new Date().toISOString()):null,b.notes??cur.notes,m[1],tenant).run();await audit(env,tenant,uid,'UPDATE','transaction',m[1]);await rebuildJobs(env,uid);return json({ok:true})}
 m=path.match(/^\/transactions\/([^/]+)\/settle$/);if(m&&method==='POST'){const cur:any=await env.DB.prepare('SELECT * FROM transactions WHERE id=? AND tenant_id=?').bind(m[1],tenant).first();if(!cur)return json({error:'Lançamento não encontrado.'},404);if(cur.status==='PAID')return json({ok:true});await env.DB.prepare("UPDATE transactions SET status='PAID',paid_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant=?").bind(new Date().toISOString(),m[1],tenant).run();await audit(env,tenant,uid,'SETTLE','transaction',m[1]);await rebuildJobs(env,uid);return json({ok:true})}
 if(m&&method==='DELETE'){await env.DB.prepare('DELETE FROM transactions WHERE id=? AND tenant_id=?').bind(m[1],tenant).run();await audit(env,tenant,uid,'DELETE','transaction',m[1]);await rebuildJobs(env,uid);return json({ok:true})}
 if(path==='/goals'&&method==='GET'){const {results}=await env.DB.prepare('SELECT * FROM goals WHERE tenant_id=? ORDER BY created_at DESC LIMIT 200').bind(tenant).all();return json({items:results})}
 if(path==='/goals'&&method==='POST'){const b=await parse(request);if(!b.name||Number(b.target)<=0)return json({error:'Meta inválida.'},400);const gid=id('goal');await env.DB.prepare('INSERT INTO goals(id,tenant_id,name,target_cents,current_cents,deadline) VALUES(?,?,?,?,?,?)').bind(gid,tenant,String(b.name).trim(),money(b.target),money(b.current),b.deadline||null).run();if(b.deadline)await scheduleJob(env,uid,'goal_deadline',`Meta: ${String(b.name).trim()}`,`A meta ${String(b.name).trim()} está próxima do prazo.`,new Date(String(b.deadline)+'T09:00:00-03:00').getTime(),b.deadline);await audit(env,tenant,uid,'CREATE','goal',gid);return json({id:gid},201)}
 m=path.match(/^\/goals\/([^/]+)$/);if(m&&method==='PUT'){const b=await parse(request);if(!b.name||Number(b.target)<=0)return json({error:'Meta inválida.'},400);await env.DB.prepare('UPDATE goals SET name=?,target_cents=?,current_cents=?,deadline=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=?').bind(String(b.name).trim(),money(b.target),money(b.current),b.deadline||null,m[1],tenant).run();await audit(env,tenant,uid,'UPDATE','goal',m[1]);return json({ok:true})}
 if(path==='/reserve'&&method==='POST'){const b=await parse(request);if(!['DEPOSIT','WITHDRAW'].includes(b.kind)||Number(b.amount)<=0)return json({error:'Movimentação inválida.'},400);if(b.kind==='WITHDRAW'){const r:any=await env.DB.prepare("SELECT COALESCE(SUM(CASE WHEN kind='DEPOSIT' THEN amount_cents ELSE -amount_cents END),0) balance FROM reserve_entries WHERE tenant_id=?").bind(tenant).first();if(money(b.amount)>Number(r.balance||0))return json({error:'Saldo insuficiente na reserva.'},409)}const rid=id('res');await env.DB.prepare('INSERT INTO reserve_entries(id,tenant_id,user_id,amount_cents,kind,note) VALUES(?,?,?,?,?,?)').bind(rid,tenant,uid,money(b.amount),b.kind,b.note||null).run();await audit(env,tenant,uid,'CREATE','reserve',rid);return json({ok:true},201)}
 if(path==='/debts'&&method==='GET'){const {results}=await env.DB.prepare('SELECT d.*,COALESCE((SELECT SUM(amount_cents) FROM debt_movements dm WHERE dm.debt_id=d.id),0) paid_cents FROM debts d WHERE d.tenant_id=? ORDER BY d.created_at DESC LIMIT 200').bind(tenant).all();return json({items:results})}
 if(path==='/debts'&&method==='POST'){const b=await parse(request);if(!b.name||Number(b.total)<0||Number(b.remaining)<0||Number(b.remaining)>Number(b.total))return json({error:'Dívida inválida.'},400);const did=id('debt');await env.DB.prepare('INSERT INTO debts(id,tenant_id,name,total_cents,remaining_cents,due_date) VALUES(?,?,?,?,?,?)').bind(did,tenant,String(b.name).trim(),money(b.total),money(b.remaining),b.due_date||null).run();await audit(env,tenant,uid,'CREATE','debt',did);return json({id:did},201)}
 m=path.match(/^\/debts\/([^/]+)\/payment$/);if(m&&method==='POST'){const b=await parse(request),d:any=await env.DB.prepare('SELECT * FROM debts WHERE id=? AND tenant_id=?').bind(m[1],tenant).first();if(!d)return json({error:'Dívida não encontrada.'},404);const amount=money(b.amount);if(amount<=0||amount>Number(d.remaining_cents))return json({error:'Abatimento inválido.'},400);const rem=Number(d.remaining_cents)-amount,dm=id('dm'),tx=id('tx');await env.DB.batch([env.DB.prepare('INSERT INTO debt_movements(id,tenant_id,debt_id,user_id,amount_cents,note) VALUES(?,?,?,?,?,?)').bind(dm,tenant,d.id,uid,amount,b.note||null),env.DB.prepare('UPDATE debts SET remaining_cents=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=?').bind(rem,d.id,tenant),env.DB.prepare("INSERT INTO transactions(id,tenant_id,user_id,type,description,amount_cents,status,paid_at,notes) VALUES(?,?,?,?,?,?,'PAID',?,?)").bind(tx,tenant,uid,'EXPENSE',`Pagamento: ${d.name}`,amount,new Date().toISOString(),b.note||null)]);await audit(env,tenant,uid,'PAYMENT','debt',d.id,{amount,remaining:rem});await rebuildJobs(env,uid);return json({ok:true,remaining_cents:rem})}
 if(path==='/settings'&&method==='GET'){let r:any=await env.DB.prepare('SELECT * FROM app_settings WHERE user_id=?').bind(uid).first();if(!r){await env.DB.prepare('INSERT OR IGNORE INTO app_settings(user_id) VALUES(?)').bind(uid).run();r=await env.DB.prepare('SELECT * FROM app_settings WHERE user_id=?').bind(uid).first()}return json(r)}
 if(path==='/settings'&&method==='PUT'){const b=await parse(request);const theme=['system','light','dark'].includes(b.theme)?b.theme:'system',mins=[0,5,15,30,60].includes(Number(b.auto_logout_minutes))?Number(b.auto_logout_minutes):15;await env.DB.prepare("INSERT INTO app_settings(user_id,theme,hide_values,auto_logout_minutes,save_login,notifications_enabled,updated_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET theme=excluded.theme,hide_values=excluded.hide_values,auto_logout_minutes=excluded.auto_logout_minutes,save_login=excluded.save_login,notifications_enabled=excluded.notifications_enabled,updated_at=CURRENT_TIMESTAMP").bind(uid,theme,b.hide_values?1:0,mins,b.save_login?1:0,b.notifications_enabled?1:0).run();return json({ok:true})}
 if(path==='/push/vapid-public'&&method==='GET')return json({publicKey:env.VAPID_PUBLIC_KEY||''})
 if(path==='/push/subscribe'&&method==='POST'){const b=await parse(request);if(!b.endpoint||!b.keys?.p256dh||!b.keys?.auth)return json({error:'Assinatura push inválida.'},400);const device=String(b.device_id||'default').slice(0,128);await env.DB.prepare("INSERT INTO push_subscriptions(id,user_id,device_id,endpoint,p256dh,auth,updated_at,revoked_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP,NULL) ON CONFLICT(endpoint) DO UPDATE SET user_id=excluded.user_id,device_id=excluded.device_id,p256dh=excluded.p256dh,auth=excluded.auth,updated_at=CURRENT_TIMESTAMP,revoked_at=NULL").bind(id('push'),uid,device,b.endpoint,b.keys.p256dh,b.keys.auth).run();await env.DB.prepare('UPDATE app_settings SET notifications_enabled=1,updated_at=CURRENT_TIMESTAMP WHERE user_id=?').bind(uid).run();return json({ok:true})}
 if(path==='/push/unsubscribe'&&method==='POST'){const b=await parse(request);if(b.endpoint)await env.DB.prepare('UPDATE push_subscriptions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=? AND endpoint=?').bind(uid,String(b.endpoint)).run();else await env.DB.prepare('UPDATE push_subscriptions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=?').bind(uid).run();await env.DB.prepare('UPDATE app_settings SET notifications_enabled=0,updated_at=CURRENT_TIMESTAMP WHERE user_id=?').bind(uid).run();return json({ok:true})}
 if(path==='/push/test'&&method==='POST'){await scheduleJob(env,uid,'test','Control','Notificações ativadas com sucesso.',Date.now());return json({ok:true})}
 if(path==='/guests'&&method==='GET'){if(s.role!=='OWNER')return json({items:[],invites:[]});const [u,i]=await Promise.all([env.DB.prepare("SELECT id,name,email,created_at FROM users WHERE tenant_id=? AND role='GUEST' ORDER BY created_at").bind(tenant).all(),env.DB.prepare('SELECT id,email,code,status,created_at FROM invites WHERE tenant_id=? ORDER BY created_at DESC LIMIT 20').bind(tenant).all()]);return json({items:u.results,invites:i.results})}
 if(path==='/guests'&&method==='POST'){if(s.role!=='OWNER')return json({error:'Somente o titular pode convidar.'},403);const c:any=await env.DB.prepare("SELECT COUNT(*) n FROM users WHERE tenant_id=? AND role='GUEST'").bind(tenant).first();if(Number(c.n)>=2)return json({error:'Limite de 2 convidados atingido.'},409);const code=String(crypto.randomUUID()).replace(/-/g,'').slice(0,8).toUpperCase(),iid=id('inv');await env.DB.prepare('INSERT INTO invites(id,tenant_id,code) VALUES(?,?,?)').bind(iid,tenant,code).run();return json({code},201)}
 return json({error:'Rota não encontrada.'},404)
}catch(e:any){console.error('CONTROL_API_ERROR',e);return json({error:e?.message==='Sessão expirada.'?'Sessão expirada.':'Erro interno. Tente novamente.'},e?.status||500)}}
