import {hashPassword,id,json,session,signSession,verifyPassword} from '../_lib/auth'
type Env={DB:any;FILES?:any;SESSION_SECRET:string};type Ctx={request:Request;env:Env;params:Record<string,unknown>}
const money=(v:any)=>Math.round(Number(v||0)*100),parse=async(r:Request)=>{try{return await r.json() as any}catch{return {}}}
const route=(p:Record<string,unknown>)=>'/'+(Array.isArray(p.path)?p.path.join('/'):String(p.path||''))
async function audit(env:Env,tenant:string,uid:string,action:string,entity?:string,eid?:string,details?:any){await env.DB.prepare('INSERT INTO audit_logs(id,tenant_id,user_id,action,entity,entity_id,details) VALUES(?,?,?,?,?,?,?)').bind(id('audit'),tenant,uid,action,entity||null,eid||null,details?JSON.stringify(details).slice(0,4000):null).run()}
export const onRequest=async({request,env,params}:Ctx)=>{try{const path=route(params),method=request.method.toUpperCase(),url=new URL(request.url)
 if(path==='/health'&&method==='GET')return json({ok:true,service:'CONTROL',version:'3.0.0'})
 if(path==='/auth/register'&&method==='POST'){const b=await parse(request);if(!b.name||!b.email||String(b.password||'').length<6)return json({error:'Preencha nome, e-mail e uma senha com 6+ caracteres.'},400);const email=String(b.email).trim().toLowerCase();if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return json({error:'Este e-mail já está cadastrado.'},409);const tenant=id('acc'),uid=id('usr'),hash=await hashPassword(String(b.password));await env.DB.batch([env.DB.prepare('INSERT INTO tenants(id,name) VALUES(?,?)').bind(tenant,String(b.tenantName||`Conta de ${b.name}`).trim()),env.DB.prepare("INSERT INTO users(id,tenant_id,name,email,password_hash,role) VALUES(?,?,?,?,?,'OWNER')").bind(uid,tenant,String(b.name).trim(),email,hash)]);const user={id:uid,tenant_id:tenant,name:String(b.name).trim(),email,role:'OWNER'};return json({token:await signSession(env,{uid,tenant,role:'OWNER'}),user},201)}
 if(path==='/auth/login'&&method==='POST'){const b=await parse(request),email=String(b.email||'').trim().toLowerCase(),u:any=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(!u||!await verifyPassword(String(b.password||''),u.password_hash))return json({error:'E-mail ou senha inválidos.'},401);const user={id:u.id,tenant_id:u.tenant_id,name:u.name,email:u.email,role:u.role};return json({token:await signSession(env,{uid:u.id,tenant:u.tenant_id,role:u.role}),user})}
 if(path==='/auth/invite'&&method==='POST'){const b=await parse(request);if(!b.code||!b.name||!b.email||String(b.password||'').length<6)return json({error:'Informe código, nome, e-mail e senha.'},400);const code=String(b.code).trim().toUpperCase(),email=String(b.email).trim().toLowerCase(),inv:any=await env.DB.prepare("SELECT * FROM invites WHERE code=? AND status='PENDING'").bind(code).first();if(!inv)return json({error:'Convite inválido ou já utilizado.'},404);if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return json({error:'E-mail já cadastrado.'},409);const c:any=await env.DB.prepare("SELECT COUNT(*) n FROM users WHERE tenant_id=? AND role='GUEST'").bind(inv.tenant_id).first();if(Number(c.n)>=2)return json({error:'Esta conta já possui 2 convidados.'},409);const uid=id('usr'),hash=await hashPassword(String(b.password));await env.DB.batch([env.DB.prepare("INSERT INTO users(id,tenant_id,name,email,password_hash,role) VALUES(?,?,?,?,?,'GUEST')").bind(uid,inv.tenant_id,String(b.name).trim(),email,hash),env.DB.prepare("UPDATE invites SET status='ACCEPTED' WHERE id=?").bind(inv.id)]);const user={id:uid,tenant_id:inv.tenant_id,name:String(b.name).trim(),email,role:'GUEST'};return json({token:await signSession(env,{uid,tenant:inv.tenant_id,role:'GUEST'}),user},201)}
 const s:any=await session(request,env);if(!s)return json({error:'Sessão expirada.'},401);const tenant=s.tenant,uid=s.uid
 if(path==='/me'&&method==='GET'){const u=await env.DB.prepare('SELECT id,tenant_id,name,email,role FROM users WHERE id=? AND tenant_id=?').bind(uid,tenant).first();return u?json(u):json({error:'Usuário não encontrado.'},404)}
 if(path==='/summary'&&method==='GET'){const r:any=await env.DB.prepare("SELECT COALESCE(SUM(CASE WHEN type='INCOME' AND status='PAID' THEN amount_cents ELSE 0 END),0) income_cents,COALESCE(SUM(CASE WHEN type='EXPENSE' AND status='PAID' THEN amount_cents ELSE 0 END),0) expense_cents,COALESCE(SUM(CASE WHEN status IN('PENDING','OVERDUE') THEN amount_cents ELSE 0 END),0) pending_cents FROM transactions WHERE tenant_id=?").bind(tenant).first(),rr:any=await env.DB.prepare("SELECT COALESCE(SUM(CASE WHEN kind='DEPOSIT' THEN amount_cents ELSE -amount_cents END),0) reserve_cents FROM reserve_entries WHERE tenant_id=?").bind(tenant).first();return json({...r,balance_cents:Number(r.income_cents)-Number(r.expense_cents),reserve_cents:Number(rr?.reserve_cents||0)})}
 if(path==='/transactions'&&method==='GET'){const page=Math.max(1,Number(url.searchParams.get('page')||1)),limit=Math.min(100,Math.max(10,Number(url.searchParams.get('limit')||50))),offset=(page-1)*limit,{results}=await env.DB.prepare('SELECT t.*,c.name category FROM transactions t LEFT JOIN categories c ON c.id=t.category_id WHERE t.tenant_id=? ORDER BY COALESCE(t.due_date,t.created_at) DESC LIMIT ? OFFSET ?').bind(tenant,limit,offset).all();return json({items:results,page,limit})}
 if(path==='/transactions'&&method==='POST'){const b=await parse(request);if(!['INCOME','EXPENSE'].includes(b.type)||!b.description||!Number.isFinite(Number(b.amount))||Number(b.amount)<0)return json({error:'Dados do lançamento inválidos.'},400);const rid=id('tx'),status=['PENDING','OVERDUE'].includes(String(b.status))?String(b.status):'PAID';await env.DB.prepare('INSERT INTO transactions(id,tenant_id,user_id,type,description,amount_cents,category_id,status,due_date,paid_at,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(rid,tenant,uid,b.type,String(b.description).trim(),money(b.amount),b.category_id||null,status,b.due_date||null,status==='PAID'?new Date().toISOString():null,b.notes||null).run();await audit(env,tenant,uid,'CREATE','transaction',rid,{type:b.type,amount:money(b.amount)});return json({id:rid},201)}
 let m=path.match(/^\/transactions\/([^/]+)$/);if(m&&method==='PUT'){const b=await parse(request),cur:any=await env.DB.prepare('SELECT * FROM transactions WHERE id=? AND tenant_id=?').bind(m[1],tenant).first();if(!cur)return json({error:'Lançamento não encontrado.'},404);const status=['PENDING','OVERDUE','PAID'].includes(String(b.status))?String(b.status):cur.status;await env.DB.prepare('UPDATE transactions SET type=?,description=?,amount_cents=?,status=?,due_date=?,paid_at=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=?').bind(b.type||cur.type,String(b.description||cur.description).trim(),b.amount===undefined?cur.amount_cents:money(b.amount),status,b.due_date??cur.due_date,status==='PAID'?(cur.paid_at||new Date().toISOString()):null,b.notes??cur.notes,m[1],tenant).run();await audit(env,tenant,uid,'UPDATE','transaction',m[1]);return json({ok:true})}
 if(m&&method==='DELETE'){if(!await env.DB.prepare('SELECT id FROM transactions WHERE id=? AND tenant_id=?').bind(m[1],tenant).first())return json({error:'Lançamento não encontrado.'},404);await env.DB.prepare('DELETE FROM transactions WHERE id=? AND tenant_id=?').bind(m[1],tenant).run();await audit(env,tenant,uid,'DELETE','transaction',m[1]);return json({ok:true})}
 if(path==='/goals'&&method==='GET'){const {results}=await env.DB.prepare('SELECT * FROM goals WHERE tenant_id=? ORDER BY created_at DESC LIMIT 200').bind(tenant).all();return json({items:results})}
 if(path==='/goals'&&method==='POST'){const b=await parse(request);if(!b.name||Number(b.target)<=0)return json({error:'Meta inválida.'},400);const gid=id('goal');await env.DB.prepare('INSERT INTO goals(id,tenant_id,name,target_cents,current_cents,deadline) VALUES(?,?,?,?,?,?)').bind(gid,tenant,String(b.name).trim(),money(b.target),money(b.current),b.deadline||null).run();await audit(env,tenant,uid,'CREATE','goal',gid);return json({id:gid},201)}
 m=path.match(/^\/goals\/([^/]+)$/);if(m&&method==='PUT'){const b=await parse(request);if(!b.name||Number(b.target)<=0)return json({error:'Meta inválida.'},400);await env.DB.prepare('UPDATE goals SET name=?,target_cents=?,current_cents=?,deadline=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=?').bind(String(b.name).trim(),money(b.target),money(b.current),b.deadline||null,m[1],tenant).run();await audit(env,tenant,uid,'UPDATE','goal',m[1]);return json({ok:true})}
 if(path==='/reserve'&&method==='POST'){const b=await parse(request);if(!['DEPOSIT','WITHDRAW'].includes(b.kind)||Number(b.amount)<=0)return json({error:'Movimentação inválida.'},400);if(b.kind==='WITHDRAW'){const r:any=await env.DB.prepare("SELECT COALESCE(SUM(CASE WHEN kind='DEPOSIT' THEN amount_cents ELSE -amount_cents END),0) balance FROM reserve_entries WHERE tenant_id=?").bind(tenant).first();if(money(b.amount)>Number(r.balance||0))return json({error:'Saldo insuficiente na reserva.'},409)}const rid=id('res');await env.DB.prepare('INSERT INTO reserve_entries(id,tenant_id,user_id,amount_cents,kind,note) VALUES(?,?,?,?,?,?)').bind(rid,tenant,uid,money(b.amount),b.kind,b.note||null).run();await audit(env,tenant,uid,'CREATE','reserve',rid);return json({ok:true},201)}
 if(path==='/debts'&&method==='GET'){const {results}=await env.DB.prepare('SELECT * FROM debts WHERE tenant_id=? ORDER BY created_at DESC LIMIT 200').bind(tenant).all();return json({items:results})}
 if(path==='/debts'&&method==='POST'){const b=await parse(request);if(!b.name||Number(b.total)<0||Number(b.remaining)<0||Number(b.remaining)>Number(b.total))return json({error:'Dívida inválida.'},400);const did=id('debt');await env.DB.prepare('INSERT INTO debts(id,tenant_id,name,total_cents,remaining_cents,due_date) VALUES(?,?,?,?,?,?)').bind(did,tenant,String(b.name).trim(),money(b.total),money(b.remaining),b.due_date||null).run();await audit(env,tenant,uid,'CREATE','debt',did);return json({id:did},201)}
 m=path.match(/^\/debts\/([^/]+)\/payment$/);if(m&&method==='POST'){const b=await parse(request),d:any=await env.DB.prepare('SELECT * FROM debts WHERE id=? AND tenant_id=?').bind(m[1],tenant).first();if(!d)return json({error:'Dívida não encontrada.'},404);const amount=money(b.amount);if(amount<=0||amount>Number(d.remaining_cents))return json({error:'Abatimento inválido.'},400);const rem=Number(d.remaining_cents)-amount,dm=id('dm'),tx=id('tx');await env.DB.batch([env.DB.prepare('INSERT INTO debt_movements(id,tenant_id,debt_id,user_id,amount_cents,note) VALUES(?,?,?,?,?,?)').bind(dm,tenant,d.id,uid,amount,b.note||null),env.DB.prepare('UPDATE debts SET remaining_cents=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=?').bind(rem,d.id,tenant),env.DB.prepare("INSERT INTO transactions(id,tenant_id,user_id,type,description,amount_cents,status,paid_at,notes) VALUES(?,?,?,?,?,?,'PAID',?,?)").bind(tx,tenant,uid,'EXPENSE',`Pagamento: ${d.name}`,amount,new Date().toISOString(),b.note||null)]);await audit(env,tenant,uid,'PAYMENT','debt',d.id,{amount,remaining:rem,transaction_id:tx});return json({ok:true,remaining_cents:rem,transaction_id:tx})}
 if(path==='/guests'&&method==='GET'){if(s.role!=='OWNER')return json({items:[],invites:[]});const [u,i]=await Promise.all([env.DB.prepare("SELECT id,name,email,created_at FROM users WHERE tenant_id=? AND role='GUEST' ORDER BY created_at").bind(tenant).all(),env.DB.prepare('SELECT id,email,code,status,created_at FROM invites WHERE tenant_id=? ORDER BY created_at DESC LIMIT 20').bind(tenant).all()]);return json({items:u.results,invites:i.results})}
 if(path==='/guests'&&method==='POST'){if(s.role!=='OWNER')return json({error:'Somente o titular pode convidar.'},403);const c:any=await env.DB.prepare("SELECT COUNT(*) n FROM users WHERE tenant_id=? AND role='GUEST'").bind(tenant).first();if(Number(c.n)>=2)return json({error:'Limite de 2 convidados atingido.'},409);const p:any=await env.DB.prepare("SELECT COUNT(*) n FROM invites WHERE tenant_id=? AND status='PENDING'").bind(tenant).first();if(Number(p.n)>=2)return json({error:'Já existem 2 convites pendentes.'},409);const b=await parse(request),code=String(crypto.randomUUID()).replace(/-/g,'').slice(0,8).toUpperCase(),iid=id('inv');await env.DB.prepare('INSERT INTO invites(id,tenant_id,email,code) VALUES(?,?,?,?)').bind(iid,tenant,b.email?String(b.email).trim().toLowerCase():null,code).run();await audit(env,tenant,uid,'INVITE','guest',iid);return json({code},201)}
 if(path==='/audit'&&method==='GET'){if(s.role!=='OWNER')return json({items:[]});const {results}=await env.DB.prepare('SELECT a.*,u.name user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE a.tenant_id=? ORDER BY a.created_at DESC LIMIT 100').bind(tenant).all();return json({items:results})}
 if(path==='/files'&&method==='POST'){if(!env.FILES)return json({error:'Upload não configurado.'},503);const fd=await request.formData(),file=fd.get('file');if(!(file instanceof File))return json({error:'Arquivo ausente.'},400);if(file.size>5_000_000)return json({error:'Arquivo acima de 5 MB.'},413);const key=`${tenant}/${uid}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;await env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type||'application/octet-stream'}});await audit(env,tenant,uid,'UPLOAD','file',key);return json({key},201)}
 return json({error:'Rota não encontrada.'},404)
}catch(e:any){console.error('CONTROL_API_ERROR',e);return json({error:'Erro interno. Tente novamente.'},500)}}
