plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rochatech.aurora'
    compileSdk 35

    defaultConfig {
        applicationId 'com.rochatech.aurora'
        minSdk 29
        targetSdk 35
        versionCode 2
        versionName '2.0.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
